feat: handle price impact on open trade
prepo-io/prepo-monorepo pull request #1128
Opened 2023-03-24 17:26 UTC by MeLlamoPablo

Blocked by #1056

2023-03-27 13:18 UTC, chrisling-dev submitted a review, later dismissed
LGTM after addressing the nit I sent to you via TG

2023-03-29 05:52 UTC, chrisling-dev requested changes
LGTM after minor nit

2023-03-29 05:52 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeButton.tsx
> +    if (unprofitable === true) return 'Unprofitable Trade'
```suggestion
    if (unprofitable) return 'Unprofitable Trade'
```

2023-04-04 04:23 UTC, chrisling-dev requested changes
LGTM after comments

2023-04-04 04:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +          console.log(wstEthQuote)
should this be removed?

2023-04-04 04:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    if (this.paymentToken.type !== 'native') return false
I think that should be in separate PR, added a ticket here with details: https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=6b4403e1ecc748a48a63e32a1f35e012&p=a69f0f4745624060bcb40c40ab860916&pm=s

2023-04-04 04:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeSummary.tsx
> +    if (ethWstEthPriceImpactTooHigh) return <RedText>Insufficient wstETH Liquidity</RedText>
Are these changes meant to be here? I'm pretty sure "Insufficient wstETH Liquidity" won't fit in the transaction summary, especially on smaller mobile screens. Should these changes be in OpenTradeButton instead of here?

2023-04-04 04:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    if (this.paymentToken.type !== 'native') return false
I think that should be in separate PR, added a ticket here with details: https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=6b4403e1ecc748a48a63e32a1f35e012&p=a69f0f4745624060bcb40c40ab860916&pm=s

2023-04-04 17:41 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +          console.log(wstEthQuote)
No, good catch, thanks!

2023-04-05 07:27 UTC, chrisling-dev requested changes
LGTM after comment

2023-04-05 07:27 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeSummary.tsx
> +      return <RedText>Unprofitable Trade</RedText>
Pretty sure it should only say Unprofitable in the summary

```suggestion
    if (withinBounds === false || ethWstEthPriceImpactTooHigh)
      return <RedText>Unprofitable</RedText>
```

2023-04-05 08:25 UTC, chrisling-dev approved these changes
LGTM

2023-04-05 08:27 UTC, merged