feat: handle multiple `TokenSender`s to calculate PPO rebates
prepo-io/prepo-monorepo pull request #1179
Opened 2023-04-04 17:38 UTC by MeLlamoPablo

🚧 Blocked by #1178 

✅ After merging this PR and #1128 we should be able to QA and deploy Deposit and Trade

------

This PR correctly handles multiple `TokenSender`s. When doing deposit and trade, there are two fees: the `deposit` fee and the `depositAndTrade` fee. The PPO rebates corresponding to those come from multiple `TokenSender`s.

In order to avoid handling this in `TradeStore`, which would introduce more complexity, I added a `FeeStore`. Now, instead of each store querying the fees, calculating the amount, the PPO rebate and its ETH value, each store would simply create one `FeeStore` for each type of fee. When creating the `FeeStore`, the caller store simply links it to a wstETH value and a token sender, and `FeeStore` does the rest.

My intention is, if this proposal is accepted, to migrate al fees to `FeeStore`, which should simplify PPO reward calculations everywhere.

`FeeStore` also logs a debug table on the console which will help us confirm that the values are correct:

<img width="1497" alt="Screenshot 2023-04-04 at 19 00 25" src="https://user-images.githubusercontent.com/11708035/229872919-88bf5926-a0f6-4f8c-828a-ded35cf4676f.png">

<img width="1497" alt="Screenshot 2023-04-04 at 19 00 57" src="https://user-images.githubusercontent.com/11708035/229872943-bfc5503c-0e77-4569-8634-909e3a017964.png">

Also, this PR introduces the `TRADE_VIA_HELPER_ENABLED` flag (currently enabled only on previews) so that we don't accidentally display PPO rewards for normal open trades. This fee is not applicable until we implement trading via `DepositTradeHelper` in #1173

2023-04-05 11:21 UTC, chrisling-dev requested changes
Nice work! I like this approach with FeeStore, only some minor comments

2023-04-05 11:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +  private get openTradeFeesInWstEthBN(): FeeStore[] {
technically the returned value isn't BigNumber nor in wst eth so this should be renamed to openTradeFees right?
```suggestion
  private get openTradeFees(): FeeStore[] {
```

2023-04-05 11:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +      openTradeFeesInWstEthBN === undefined
and should this check be removed since it will never be undefined? or updated to something like `openTradeFees.length === 0` ?

2023-04-05 11:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +    }
would prefer that we use `forEach` if possible, for better code readability and also less room for mistake
```suggestion
    fees.forEach((fee) => {
      if (fee.feeAmountInWstEth === undefined) return undefined
      total = total.add(fee.feeAmountInWstEth)
    })
```

2023-04-05 11:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +    }
ditto if we could use forEach

2023-04-05 11:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +      })
I like this debugInfo, and think we should keep it, but could we hide it with isProduction check?

2023-04-05 11:59 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +      })
Mm, not sure about that. In the past we've had the fee appear to be wrong in production and debugging that was a bit tedious. If we've had that it would have been easy to inspect how the fee was being calculated.

My intention was to enable it on production for a few days and hide it or remove it some days after. What do you think?

2023-04-05 12:03 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +    }
That wouldn't work because the `return undefined` is intended to return from the entire `getTotalFeeInWstEth`, and here it would return from the inline `forEach` function instead.

I tried to do `for..of` for better readability but our [`no-restricted-syntax` ESLint rule](https://eslint.org/docs/latest/rules/no-restricted-syntax) prevents that.

2023-04-05 12:10 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +  private get openTradeFeesInWstEthBN(): FeeStore[] {
Good catch!

2023-04-05 12:11 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +      openTradeFeesInWstEthBN === undefined
Actually I added `| undefined` to the type instead, because I think that an empty array is not a good indication that the fees are loading (could be that there are no fees). So thanks for the feedback.

2023-04-06 04:00 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/FeeEntity.ts
> +    }
oh you're right, it needs to return, np!

2023-04-06 05:41 UTC, chrisling-dev approved these changes
LGTM, a PR like this could be split into smaller PRs for better reviewability, I'd probably do:  
- First PR for FeeStore without reward stuff, this way the first PR would only ever have fee stuff
- Second PR for PPO reward

that way both PRs would be much easier to review IMO

2023-04-06 09:10 UTC, merged