feat: add simulator page [🚧 WIP]
prepo-io/prepo-monorepo pull request #1206
Opened 2023-04-07 17:56 UTC by MeLlamoPablo

🚧 WIP

Blocked by #1205

2023-04-15 00:16 UTC, chrisling-dev requested changes
Thoughts on design, looking at code now

The input width seems wrong in preview? and width changes as I type 

Thoughts on design, feels weird that nothing is in the center (no main CTA), if we're going with this approach, I think the simulator should be in the center and settings to the right of it (like trade page)

<img width="312" alt="Screenshot 2023-04-15 at 8 09 58 AM" src="https://user-images.githubusercontent.com/81092286/232172824-0b7fd7d5-75f0-46f6-a197-4a051c8cb34c.png">

2023-04-15 00:16 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/DirectionRadio.tsx
> +        line-height: ${spacingIncrement(14)};
border radius for small size should be 12px so it's not fully rounded. I don't think we use fully rounded elements anywhere

2023-04-15 01:29 UTC, chrisling-dev requested changes

2023-04-15 01:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSettings.tsx
> +    error={!isValid}
Should add block to keep it fill the width

```suggestion
  <Input
    block
    error={!isValid}
```

2023-04-15 01:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSettings.tsx
> +    }}
There's probably some weird behaviour about this, try typing 10. in the valuation input and it just clears the input. Actually just typing "." or "," will empty the input and cause the other input to be inValid

I think the inputs could just be integer?

2023-04-15 01:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorPage.tsx
> +  const exitPrice = useFormValue<number | undefined>(0.6)
default exit should be max profit scenario, 0.9?

2023-04-15 01:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorPage.tsx
> +  return [+valuationMin >= 0 && +valuationMin <= 1000, +valuationMax >= 0 && +valuationMax <= 1000]
both of these seems to be doing almost exactly the same thing except hard coded min max, should we just make it a single `validateRange({max, min, maxCap, minCap})` ?

2023-04-15 01:33 UTC, chrisling-dev reviewed
Also should settings card be full width on mobile? Not sure if this would look too small on mobile
<img width="447" alt="Screenshot 2023-04-15 at 9 32 55 AM" src="https://user-images.githubusercontent.com/81092286/232176813-af97e56f-0929-4c3e-99cb-c7b7461e429d.png">

2023-04-17 05:17 UTC, MeLlamoPablo commented on packages/prepo-ui/src/components/Icon/icon-components/application/SettingsIcon.tsx
> +      color={color}
Reverted the change, we don't need the settings icon anymore

2023-04-17 05:46 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSettings.tsx
> +    }}
> I think the inputs could just be integer?

I think they should allow decimals

> There's probably some weird behaviour about this, try typing 10. in the valuation input and it just clears the input. Actually just typing "." or "," will empty the input and cause the other input to be inValid

Fixed this by switching to type="text"

2023-04-24 06:31 UTC, chrisling-dev requested changes
Estimated Profit seems wrong

Estimated Profit should always be same as Max Profit in max profit scenario for any parameters set. Try changing payout range to anything other than 10 - 90 and the max profit wouldn't be same as estimated profit. For example, if we do 30% - 50%, it means that the cheapest entry would be 0.3 per long token, and max profit would be selling at 0.5 per long token, 66.667% profit, which is correct for Max Profit but wrong for Estimated Profit

2023-04-24 06:32 UTC, chrisling-dev commented
> Estimated Profit seems wrong
> 
> Estimated Profit should always be same as Max Profit in max profit scenario for any parameters set. Try changing payout range to anything other than 10 - 90 and the max profit wouldn't be same as estimated profit. For example, if we do 30% - 50%, it means that the cheapest entry would be 0.3 per long token, and max profit would be selling at 0.5 per long token, 66.667% profit, which is correct for Max Profit but wrong for Estimated Profit

Seems to be a state management issue, if you change the valuation range after changing payout range, then drag the slider again, the Estimated Profit becomes correct again, but if you "reset", the Estimated Profit is wrong again?

2023-04-28 06:38 UTC, chrisling-dev requested changes
The estimated profit is wrong for Short

I have suggested approach to correct the prices:

`entryPrice` and `exitPrice` in `Simulator.tsx` should always be the actual price to the selected direction, since that helps with more accurate pnl calculation. So we should remove `const position = direction === 'long' ? distance : 1 - distance` in mapDistanceToPrice

Now, removing that will cause valuation shown on handles to be wrong, which is expected because now prices are accurate to their selected direction (e.g. best entry for long is payoutRange[0] and best entry for short is payoutRange[1]), but calculateValuation function takes `longTokenPrice` and specified in the function's parameter

So we'll do another variable to compute long price for both entry and exit

2023-04-28 06:38 UTC, chrisling-dev commented on packages/prepo-ui/src/components/Simulator/Simulator.tsx
>    const exitValuation = getValuationForPrice(exitPrice)
```suggestion

  const entryLongPrice = direction === 'long' ? entryPrice : 1 - entryPrice
  const exitLongPrice = direction === 'long' ? exitPrice : 1 - exitPrice
  const entryValuation = getValuationForPrice(entryLongPrice)
  const exitValuation = getValuationForPrice(exitLongPrice)
```

2023-04-28 06:38 UTC, chrisling-dev commented on packages/prepo-ui/src/components/Simulator/Simulator.tsx
> +  const position = direction === 'long' ? distance : 1 - distance
probably don't want to do this here because this distance is already "reverted" (e.g. regardless of direction, best entry is always 0)

So if I'm shorting, and simulating with entry at best rate (distance: 0), I want to get payout at payout[0], if you do 1 - distance here I will get payout[1]


```suggestion
  const position = direction === 'long' ? distance : 1 - distance
```

2023-04-28 06:38 UTC, chrisling-dev commented on packages/prepo-ui/src/components/Simulator/Simulator.tsx
> +  direction: 'long' | 'short'
so you can remove the need for direction here and remove everywhere that is passing direction to this function (e.g. including in SimulatorCard)

2023-04-28 07:01 UTC, chrisling-dev requested changes
This PR has been understandably, pretty complex to review, so I'm suggesting a few improvements on code readability

2023-04-28 07:01 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorCard.tsx
> +        })}
After removing `direction` in `mapDistanceToPrice`: 

```suggestion
        entryPrice={mapDistanceToPrice({ data, distance: entryDistance })}
        exitPrice={mapDistanceToPrice({ data, distance: exitDistance })}
```

2023-04-28 15:45 UTC, MeLlamoPablo commented on packages/prepo-ui/src/components/Simulator/Simulator.tsx
> +  const exitX = direction === 'long' ? exitDistance : 1 - exitDistance
Great catch! The code is already prepared to handle the case of `entryX` and `exitX` being undefined, so what I need to do is just default to undefined if the distance is undefined.

2023-04-28 15:58 UTC, MeLlamoPablo commented
@chrisling-dev thanks for the fantastic feedback! Your suggestions make a lot of sense.

I didn't have the chance to give you an overview of the latest refactor in 4041d87. You were able to understand it well, I just wanted to talk about the rationale behind doing so:

The Simulator, when it was made for the trade page, was designed with the assumption that the valuation and price ranges wouldn't change. With these assumptions, having the source of truth be `entryPrice` and `exitPrice` makes sense.

However, on the simulator page this assumption no longer holds true, which is what caused the bug you detected:

> Estimated Profit seems wrong
> 
> Estimated Profit should always be same as Max Profit in max profit scenario for any parameters set. Try changing payout range to anything other than 10 - 90 and the max profit wouldn't be same as estimated profit. For example, if we do 30% - 50%, it means that the cheapest entry would be 0.3 per long token, and max profit would be selling at 0.5 per long token, 66.667% profit, which is correct for Max Profit but wrong for Estimated Profit

One solution would've been to sync the prices when the price range changes, but this added more complexity. Instead I decided to change the source of truth to be something different. It couldn't have been `entryX` and `exitX` because this wouldn't change when you changed direction, requiring also more syncing. This is why I introduced the "distance" concept, because it is independent of the price range and the direction.

2023-05-01 05:32 UTC, chrisling-dev requested changes
build is still failing, could you look into this? @MeLlamoPablo

2023-05-01 09:26 UTC, MeLlamoPablo commented
Fixed, sorry, for some reason errors weren't popping up on my IDE

2023-05-01 11:45 UTC, chrisling-dev approved these changes
LGTM!

2023-05-01 11:46 UTC, merged