[WIP] Add `EtherAmount` to simplify operating with ETH and wstETH
prepo-io/prepo-monorepo pull request #1248
Opened 2023-04-27 17:25 UTC by MeLlamoPablo

Blocked by #1247 

🚧 WIP

2023-05-01 11:44 UTC, MeLlamoPablo commented
@chrisling-dev I think this is ready to receive feedback, even though the tests are failing. Before putting more work into this I'd like to make sure that we're on the same page.

2023-05-04 06:49 UTC, chrisling-dev commented
Hey @MeLlamoPablo could you help rebase this PR for review

2023-05-04 11:01 UTC, MeLlamoPablo commented
Done @chrisling-dev

2023-05-05 06:21 UTC, chrisling-dev requested changes
This PR is too large for me to review confidently, could you break it down into smaller PRs? I would at least have:

- Deposit: 1 PR
- Withdraw: 1 PR
- Trade: 1 PR

The idea is that each PR should not affect more than 1 feature so it's easier to test, because this PR is quite complex

Also try to avoid any irrelevant changes like the comment in Layout.tsx

2023-05-08 15:39 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/utils/fraction-utils.ts
> +export function mul(number: BigNumber | BigAmount, [num, den]: Fraction): BigNumber | BigAmount {
These are [Typescript Function Overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads). They provide signatures more precise than the implementation signature.

In this case, the implementation signature can take either `BigNumber` or `BigAmount` and can return either `BigNumber` or `BigAmount`. If we had only that, we'd have to cast the result to what we need every time.

With the two above overloads we can specify more precise types:

* If the input is `BigNumber`, the result is `BigNumber`
* If the input is a child of `BigAmount`, the result is that child of `BigAmount`

2023-05-08 16:58 UTC, MeLlamoPablo commented
@chrisling-dev opened #1310 with just the `EtherAmount` class and its tests. This PR is intended to hold all WIP changes but not intended to be merged. After that one is merged I'll continue splitting this one.

2023-05-08 17:01 UTC, MeLlamoPablo commented
> Also try to avoid any irrelevant changes like the comment in Layout.tsx

This is not an irrelevant change, the build would fail without it due to the ESLint change

2023-05-11 10:40 UTC, closed without merging