feat: added prepo-io/stores to prepo-stores monorepo
prepo-io/prepo-monorepo pull request #125
Opened 2022-06-09 17:46 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=18614b05af154f39ac3bed844f6ccb3b

2022-06-09 18:01 UTC, r0x4xn commented
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-3slphmkdu-prepo.vercel.app'>https://react-boilerplate-3slphmkdu-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

2022-06-09 18:10 UTC, r0x4xn commented
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-gk97cv6s9-prepo.vercel.app'>https://core-dapp-gk97cv6s9-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

2022-06-10 11:55 UTC, r0x4xn submitted a review, later dismissed
CHANGELOG.md should not be migrated

2022-06-10 11:55 UTC, r0x4xn commented on packages/prepo-stores/README.md
> +# @prepo-io/stores
rename this one, it's now called `prepo-stores`

2022-06-10 11:55 UTC, r0x4xn commented on packages/prepo-stores/README.md
> +```
All the content on the readme is not relevant anymore

2022-06-10 11:55 UTC, r0x4xn commented on packages/prepo-stores/src/ContractStore.ts
> +// import { SupportedContractName } from 'prepo-constants'
We can remove this comment if we are not using this

2022-06-13 01:14 UTC, chrisling-dev requested changes
Nice, just 2 comments

2022-06-13 01:14 UTC, chrisling-dev commented on packages/prepo-stores/README.md
> +# @prepo-stores
Let's name this consistently across different packages
```suggestion
# prePO Stores package
```

2022-06-13 09:52 UTC, chrisling-dev approved these changes

2022-06-13 11:38 UTC, merged