feat: pnl position
prepo-io/prepo-monorepo pull request #128
Opened 2022-06-10 08:08 UTC by chrisling-dev

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=03bac041792a467d9624043157ab1034

2022-06-10 08:57 UTC, r0x4xn requested changes

2022-06-10 08:57 UTC, r0x4xn commented on apps/subgraphs/core-dapp/package.json
> +  "name": "boilerplate",
change to core-dapp-subgraph

2022-06-10 08:57 UTC, r0x4xn commented on apps/subgraphs/core-dapp/package.json
> +  "description": "prePO subgraph boilerplate",
change description too

2022-06-10 08:57 UTC, r0x4xn commented on package.json
> +      "apps/subgraphs",
I believe this should be `apps/subgraphs/*`

2022-06-10 08:57 UTC, r0x4xn commented on apps/subgraphs/core-dapp/tsconfig.json
> +  }
Can remove these, we already have them on the base tsconfig. It can just be

```suggestion
  "compilerOptions": {
    "target": "es5",
    "outDir": "dist"
  }
```

2022-06-10 08:57 UTC, r0x4xn commented on apps/subgraphs/core-dapp/src/utils/math.ts
> +  if (exchangeDecimals == ZERO_BI) {
Why disabling `eqeqeq`?

2022-06-10 08:57 UTC, r0x4xn commented on apps/subgraphs/core-dapp/src/utils/math.ts
> +export function sqrtPriceX96ToTokenPrices(
Do we have a reference for this one?

2022-06-10 11:17 UTC, chrisling-dev commented on apps/subgraphs/core-dapp/src/utils/math.ts
> +export function sqrtPriceX96ToTokenPrices(
yeap! Added a comment for this

2022-06-10 11:18 UTC, chrisling-dev commented on apps/subgraphs/core-dapp/src/utils/math.ts
> +  if (exchangeDecimals == ZERO_BI) {
This was a piece of code copied from uniswap, I did a refactor to do proper comparison

2022-06-13 12:57 UTC, r0x4xn approved these changes
Small comment on carets only. Good job! (Don't forget to do yarn install after removing them :) )

2022-06-13 13:17 UTC, merged