feat: add simulate button
prepo-io/prepo-monorepo pull request #1287
Opened 2023-05-04 15:36 UTC by MeLlamoPablo

Blocked by #1286 

https://www.notion.so/prepo/Market-Details-simulate-button-6d9e731f7a764725a632a26aaa3146f0

https://user-images.githubusercontent.com/11708035/236257254-6aa7445a-3d9c-4586-b552-3ee6f7cdaa60.mp4

2023-05-05 04:55 UTC, chrisling-dev requested changes

2023-05-05 04:55 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/MarketDetails.tsx
> +
remove this?

2023-05-05 04:55 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/TradeSimulator.tsx
> +} from "prepo-ui"
Is this changed by eslint? Our app uses single quote (enforced by eslint and prettier), it's weird that all other packages is still using single quote except for this one?

```suggestion
} from 'prepo-ui'
```

2023-05-05 04:55 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/MarketDetails.tsx
> +            $visible={!simulatorOpen && !selectedMarket.resolved}
Would recommend making a computed `showSimulator` state in TradeStore so the same logic can be reused across MarketDetails and TradeSimulator

2023-05-05 04:55 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/MarketDetails.tsx
> +            // Hidden rather than unmounted so there's no height jump
I think can remove this comment

2023-05-05 08:36 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/TradeSimulator.tsx
> +} from "prepo-ui"
So the problem I had is that my git hooks weren't running for some reason. A simple `husky install` fixed it, so I shouldn't have these kind of problems moving forward.

2023-05-08 02:07 UTC, chrisling-dev approved these changes
LGTM!

2023-05-08 09:55 UTC, merged