Feat/custom rpc UI
prepo-io/prepo-monorepo pull request #1435
Opened 2023-06-12 04:05 UTC by chrisling-dev

2023-06-12 09:37 UTC, MeLlamoPablo requested changes

2023-06-12 09:37 UTC, MeLlamoPablo commented on packages/prepo-stores/src/utils/CustomProviders.ts
> +      // calls would lose observability if all providers were previously failing
Could you elaborate on this problem? I'm not sure I understand it.

2023-06-13 04:53 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/CustomProviders.ts
> +      // calls would lose observability if all providers were previously failing
so basically if all the default list is failing, and you try to add a custom RPC to recover it, nothing will react. You'll see the network requests to failing RPCs are stopped and it's now sending to new RPC, but the read values are no longer updated. I still don't know what the root cause is yet, wasn't able to find out

In the case of Web3Provider it was because a `called` flag is preventing the call from being retriggered but that fix doesn't solve this, so the best solution I have so far is to refresh the page so the FallthroughProviders can be re-initialized. Explained the impact on UX of this refresh

2023-06-13 05:11 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/CustomProviders.ts
> +      // calls would lose observability if all providers were previously failing
nvm I found a solution to this after some further exploration

2023-06-13 05:20 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/RpcSettings.tsx
> +  }
I don't agree with creating a component within RpcSettings as that makes the code very confusing IMO

I don't think this necessary has to be a component and this is a pretty common pattern, it's pretty much the same as doing this but returning a JSX instead of string:

```
const buttonText = useMemo(() => {
   if(loading) return 'Loading'
   if(InsufficientLiquidity) return 'Insufficient Liquidity'
   return "Trade"
}, [...])

return <Button>{buttonText}</Button>
```
 We can also do useMemo here like in the example I gave above but the computation here isn't expensive at all

If we want to do <StatusIcon /> we should do it outside the component with proper props passing but that'd be overkill for a component that isn't reused

2023-06-13 05:29 UTC, chrisling-dev commented on packages/prepo-ui/src/components/Spinner/index.tsx
> +
Good suggestion, the type will be inferred, no? And we can just import `@ant-design/icons/LoadingOutlined` instead

```
const SpinFC = dynamic(() => import('antd').then(({ Spin }) => Spin))
const LoadingOutlined = dynamic(() => import('@ant-design/icons/LoadingOutlined'))

```

2023-06-13 10:59 UTC, MeLlamoPablo approved these changes
LGTM!

2023-06-13 11:16 UTC, merged