Feat/wallet provider
prepo-io/prepo-monorepo pull request #1436
Opened 2023-06-12 07:32 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=00b907a28d144d1d9dadd16c96b536ea&p=ac7e08fcf5f646bd99d55dd8f24df6d1&pm=s

2023-06-12 10:28 UTC, MeLlamoPablo requested changes

2023-06-12 10:28 UTC, MeLlamoPablo commented on packages/prepo-stores/src/ContractStore.ts
> +                if (isImportantError(error) && process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production')
Should use `isProduction` instead?

2023-06-12 10:28 UTC, MeLlamoPablo commented on packages/prepo-stores/src/utils/CustomProviders.ts
> +  }
I think a more simple way of doing this would be to have:

```typescript
class FallThroughProviders {
  // ...

  private _walletProvider?: ethers.providers.Web3Provider
  private _defaultProviders: ethers.providers.JsonRpcProvider[] = []

  get providers(): ethers.providers.JsonRpcProvider[] {
    if (this._walletProvider)
      return [this._walletProvider, ...this._defaultProviders]
    return this._defaultProviders
  }

  setWalletProvider(provider?: ethers.providers.Web3Provider): void {
    this._walletProvider = provider
  }

  // ...
}
```

This way we don't have to worry about checking whether the wallet provider is or isn't set, or manipulating indexes.

2023-06-13 02:05 UTC, chrisling-dev commented on packages/prepo-stores/src/ContractStore.ts
> +                if (isImportantError(error) && process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production')
this is ContractStore and isProduction isn't exposed here

2023-06-13 02:10 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/CustomProviders.ts
> +  }
That was my initial approach but there was some observability issue (which I later fixed in contract store), let me try this again with that fix

2023-06-13 05:47 UTC, chrisling-dev commented on packages/prepo-stores/src/ContractStore.ts
> +                if (isImportantError(error) && process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production')
Resolving this because the fix is brought forward to previous PR

2023-06-13 10:59 UTC, MeLlamoPablo commented on packages/prepo-stores/src/ContractStore.ts
> +                if (isImportantError(error) && process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production')
> this is ContractStore and isProduction isn't exposed here

Didn't realize this, sorry!

2023-06-13 11:00 UTC, MeLlamoPablo approved these changes

2023-06-13 11:34 UTC, merged