feat: handle redemption fee of MarketEntity v1.1
prepo-io/prepo-monorepo pull request #1453
Opened 2023-06-19 06:51 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=1160865fbe4c4639af9d63918c7b7d17&p=4e40a878c55845ffb887e9d2bddda10f&pm=s

2023-06-19 10:18 UTC, MeLlamoPablo requested changes

2023-06-19 10:18 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/AddressBeaconEntity.ts
> +  }
Should `get` be `observable`?

2023-06-19 10:18 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/ResourceStore.ts
> +  addressBeacons: Record<string, AddressBeaconEntity> = {}
```suggestion
  addressBeacons: Record<string, AddressBeaconEntity | undefined> = {}
```

2023-06-19 10:18 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/BaseMarketEntity.ts
> +  }
I think it's better to make `BaseMarketEntity` `abstract` and then do:

```ts
abstract redemptionFee: Fraction | undefined
```

Then we can override this on `MarketEntity` and `MarketEntity_v1_1`

2023-06-19 10:19 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/AddressBeaconEntity.ts
> +  }
yeap!

2023-06-19 11:29 UTC, MeLlamoPablo approved these changes
Unblocking this - LGTM after comments

2023-06-20 03:19 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/BaseMarketEntity.ts
> +  }
Not sure why but making redemptionFee causes the logic in MarketEntity to be skipped and it keeps returning undefined (even console.log in MarketEntity's redemptionFee is skipped), I'll keep it untouched for now

2023-06-21 04:07 UTC, merged