fix: add deeplink warning for metamask on mobile
prepo-io/prepo-monorepo pull request #1537
Opened 2023-07-27 07:06 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=1160865fbe4c4639af9d63918c7b7d17&p=4088710e7c50400b8260626aa8616532&pm=s

2023-07-27 12:34 UTC, MeLlamoPablo requested changes
Two suggestions:

1. We can implement the "open metamask directly" logic by wrapping the injected module:

    ```ts
    const isInjected = typeof window !== 'undefined' && 'ethereum' in window

    const customInjected: WalletInit = (walletHelpers) => {
      const modules = injected(walletHelpers)
      // Never happening, the injected provider always returns an array
      if (!Array.isArray(modules)) return modules
  
      return modules.map((module) => ({
        ...module,
        getInterface: (interfaceHelpers) => {
          if (!isInjected) {
            window
              .open(
                isMobile()
                  ? `https://metamask.app.link/dapp/${window.location.hostname}`
                  : 'https://metamask.io/download',
                '_blank'
              )
              .focus()
            // An empty message aborts the connection process but doesn't show an error
            throw new Error()
          }
  
          return module.getInterface(interfaceHelpers)
        },
      }))
    }
    ```

    Then we can simply do:

    ```ts
    return {
      wallets: [customInjected, safeWallet, coinbaseWallet, walletConnect],
      // ...
    }
    ```

    This will connect Metamask if the user has it and will open the downloads page if they don't. After this, we can drop the whole `walletUnavailableMessage` logic.

2. If Metamask is not available, I don't believe we should show it as the first option. There are wallets with better UX. For example, the Coinbase Wallet has built in backups whereas Metamask doesn't AFAIK. And soon we will have an email/social login option which is more UX-friendly.

    To do this, we can take the `isInjected` variable from the code above, and do:

    ```ts
    return {
      wallets: [
        isInjected ? injected : undefined,
        safeWallet,
        coinbaseWallet,
        walletConnect,
        !isInjected ? injected : undefined,
      ].filter((wallet): wallet is NonNullable<typeof wallet> => !!wallet),
      // ...
    }
    ```

2023-07-27 12:34 UTC, MeLlamoPablo commented on packages/prepo-stores/src/utils/onboard-config.ts
> +      if (!isSafariDesktop && metamask) walletModules.unshift(metamask)
We're using the `sort` option to remove a wallet, which feels very weird to me.

The injected module offers a handy `filter` property which I believe should achieve the same:

```ts
filter: {
  [ProviderLabel.Detected]: ['Safari', 'desktop']
},
```

2023-07-27 12:40 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/onboard-config.ts
> +      let message = `Oops ${wallet.label} is unavailable!`
This was just the default message recommended by blocknative haha, yeap sounds good

2023-07-27 12:42 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/onboard-config.ts
> +      if (!isSafariDesktop && metamask) walletModules.unshift(metamask)
the `filter` property doesn't work properly. If you do ['Safari'], it will somehow still show on all safari browsers. And if you include `desktop`, now all desktop browsers won't see the detected wallet, even if it's chrome. This was my first attempt

2023-07-27 12:42 UTC, chrisling-dev commented
> We can implement the "open metamask directly" logic by wrapping the injected module:

interesting! I'll try that out

2023-07-28 09:15 UTC, MeLlamoPablo approved these changes
Thanks for iterating!

2023-07-28 09:40 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/onboard-config.ts
> +         */
Yes we do if we want to support other new mainstream wallets that are not injected on mobile (e.g. the new Uniswap mobile wallet, MEW wallet, rainbow and etc)

The comment is about a refactor, it would be annoying to do
```
if(label === metamask && !hasInjected) {
   // handle  metamask edge cases
} else if(label === mev && !hasInjected) {
   // handle mev edge cases
} else if(...) { ... }
```

Since we don't support any other wallets this way except for metamask, the current solution is good enough. The comment simply act as a pointer in case we revisit and plan to add more wallets support, which we actually have a ticket for

2023-07-28 09:40 UTC, merged

2023-07-28 11:29 UTC, MeLlamoPablo commented on packages/prepo-stores/src/utils/onboard-config.ts
> +         */
But we do support other injected wallets already. For example this is what happens if you visit prePO with Encrypt:

<img width="826" alt="Screenshot 2023-07-28 at 13 28 15" src="https://github.com/prepo-io/prepo-monorepo/assets/11708035/cd3f2431-37a7-4935-99df-f1ff29548b19">

My point is that when there is no injected wallet we only have to show Metamask, not the others. So there's no need for this hypothetical refactor.