feat: resolve .eth and .arb names via Space ID
prepo-io/prepo-monorepo pull request #1560
Opened 2023-08-10 12:44 UTC by MeLlamoPablo

<img width="275" alt="Screenshot 2023-08-10 at 14 41 06" src="https://github.com/prepo-io/prepo-monorepo/assets/11708035/cae88f87-5453-4b79-b51c-7a4157dcbe0d">

<img width="275" alt="Screenshot 2023-08-10 at 14 41 42" src="https://github.com/prepo-io/prepo-monorepo/assets/11708035/21db8be7-c646-4bb8-98fd-219b88c974cc">

This PR integrates ENS and .arb resolution via [Space ID](https://space.id/). If the connected wallet resolves to a .eth or .arb name the UI will display it (giving priority to .arb). Additionally, if it doesn't have a .arb name but has a .eth name with an avatar, the avatar will also be displayed.

2023-08-10 15:38 UTC, chrisling-dev requested changes

2023-08-10 15:38 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +  dotEthName?: string
could we make a type for this

2023-08-10 15:38 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +  }
and reuse here
```suggestion
  Props & SpaceID
```

2023-08-10 15:38 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +    return { dotEthName: dotEthName ?? undefined }
Wouldn't the empty value of dotArbName and dotEthName be undefined?
```suggestion
    return { dotArbName, dotEthName }
```

2023-08-10 15:38 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +  </Suspense>
Doesn't seem like we need suspense here

The WalletIdentity could just implement the useSpaceId hook and the jsx directly. Since the fallback is PlainAddressIdentity without ens name `{dotArbName ?? dotEthName ?? getShortAccount(address)}` would essentially achieve the same thing:

- when spaceid isn't loaded: show address
- if spaceid is loaded: show ens
- if unavailable: shw address

2023-08-10 15:44 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +  return <PlainAddressIdentity address={address} dotArbName={dotArbName} dotEthName={dotEthName} />
irrelevant if you take the approach I recommend in the last comment

2023-08-10 16:18 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +    return { dotEthName: dotEthName ?? undefined }
No, because the Space ID SDK returns null if they can't find an ID, so I'd rather not mix null and undefined

2023-08-10 16:48 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/components/SettingsMenu/WalletIdentity.tsx
> +  </Suspense>
Yes, `usePromise` would essentially achieve the same thing. The reason I did suspense is so that we easily could migrate this code to another codebase (also why I'm not storing the results of space ID/avatar on a store and just pulling the data on hooks). But I'm not opposed to using `usePromise` here, if we ever migrate this we can consider switching back.

2023-08-11 01:45 UTC, chrisling-dev approved these changes
LGTM after comments

2023-08-11 01:45 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/hooks/useSpaceId.ts
> +
since arbitrumProvider is not reused I reckon we could just create it within the callback?
```suggestion
  const result = usePromise(
    useCallback(async () => {
      // @ts-expect-error - Library does not provide types
      const { default: SID, getSidAddress } = await import('@siddomains/sidjs')
      const arbProvider = coreProvider.network.chainId === NETWORKS.arbitrumOne.chainId
          ? coreProvider
          : createFallthroughProvider(NETWORKS.arbitrumOne)
```

2023-08-11 01:45 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/hooks/useSpaceId.ts
> +
also the pattern is more consistent to how `ethProvider` is created

2023-08-11 10:01 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/hooks/useSpaceId.ts
> +      return { dotEthName: dotEthName ?? undefined }
This is done intentionally, because `useSpaceId` should decide which identity is displayed in case the user has multiple. Since `.arb` has priority, if the user has both, `.eth` is not returned. This is important because in case the user has `.arb` and `.eth`, we don't want to display the `.eth` avatar (and `.arb` has no avatar suppport, so displaying `.eth` avatar with `.arb` name can be confusing)

So instead to avoid being misleading I've updated the `SpaceId` type to explicitly describe that both can't coexist at the same time.

2023-08-11 10:13 UTC, merged