feat: update onboard to v2, removed v1
prepo-io/prepo-monorepo pull request #157
Opened 2022-06-17 11:42 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=58e036feb34c45b890079dea31ccc78d

2022-06-17 15:10 UTC, r0x4xn commented
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-71dv9v6hs-prepo.vercel.app'>https://core-dapp-71dv9v6hs-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

2022-06-20 03:59 UTC, chrisling-dev requested changes
There seems to be a bug when you disconnect and connect again, it will show:
![Screenshot 2022-06-20 at 11 59 28 AM](https://user-images.githubusercontent.com/81092286/174522833-c1e49659-5dc3-4e42-ad67-c35b2092d8a6.png)

2022-06-20 03:59 UTC, chrisling-dev commented on packages/prepo-utils/src/formatNumber.ts
> +export const chainIdToHexString = (chainId: ChainId): string => `0x${chainId.toString(16)}`
Could we move this to it's own file `chainIdToHexString.ts`? I think we've previously discussed to keep each util function in it's own file with it's named after itself so it's more organized

2022-06-20 03:59 UTC, chrisling-dev commented on packages/prepo-stores/src/utils/onboard-config.ts
> +export const chainIdToHexString = (chainId: ChainId): string => `0x${chainId.toString(16)}`
this is repeated in in prepo-utils, could just use the one in prepo-utils?

2022-06-20 08:53 UTC, georgesmithishere commented
> chainIdToHexString

fixed, thanks

2022-06-20 09:06 UTC, r0x4xn requested changes
Same behavior as Chris. After disconnecting wallet and try to connect again it get's a bit weird. 
Are we really cleaning the state of everything when we disconnect?

2022-06-20 09:06 UTC, r0x4xn commented on packages/prepo-stores/src/utils/onboard-config.ts
> +      ],
We used to have support for more wallets. Can we add them here too?

2022-06-20 12:24 UTC, georgesmithishere commented on packages/prepo-stores/src/utils/onboard-config.ts
> +      ],
we support huge amount of wallets, this is what injected wallets do, it tracks all installed wallets you have,
here is recommendation when you don't have any wallets installed - do we want to add more wallet here?

2022-06-27 14:05 UTC, r0x4xn approved these changes

2022-07-04 10:23 UTC, merged