fix: fixed slippage issue
prepo-io/prepo-monorepo pull request #166
Opened 2022-06-21 19:41 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=3e63bca1592341238362137142c52422

2022-06-22 12:16 UTC, r0x4xn requested changes
![image](https://user-images.githubusercontent.com/85726992/175022733-51846809-8b30-40a1-8c66-a1af6e4881f3.png)

What does expected output amount is representing here? 

There's no way the user will not get $182 after opening a trade position of $100 just instantly.
Feels that the value you are getting back from the `quoteExactInputSingle` should be manipulated to calculate this a bit different. I would expect a value very close to the `$100` here

2022-06-22 12:16 UTC, r0x4xn commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    const tokenAddressTo = selectedToken.address ?? ''
We should check that this value is truthy and not fallbacking to an empty string. That will cause an error

2022-06-22 12:16 UTC, r0x4xn commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +      const result = await func(tokenAddressFrom, tokenAddressTo, fee, this.openTradeAmount, 0)
What is the `0` representing here?

2022-07-11 08:01 UTC, chrisling-dev requested changes

2022-07-11 08:52 UTC, georgesmithishere commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    }
thanks!

2022-07-12 06:53 UTC, chrisling-dev requested changes
some minor comments

2022-07-12 06:58 UTC, chrisling-dev requested changes

2022-07-12 06:58 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    const amountOut = await this.quoteExactInput(selectedMarket)
another UX issue here is that, because there's no single source of truth for amountOut, users could be viewing valuation based on amountOut at time X, and place a trade at time Y when the rate has changed, I have a supporting PR to help solve this

2022-07-12 06:58 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    const amountOut = await this.quoteExactInput(selectedMarket)
Feel free to review and merge if all looks good: https://github.com/prepo-io/prepo-monorepo/pull/204

2022-07-12 08:51 UTC, liamaharon commented
Notes from FE sync

Let's follow Uniswap and also show
1. ~Average Valuation Price~ -> Expected Valuation [before slippage]
2. Valuation Impact [average valuation - current valuation (percent change)]
3. Maximum Valuation After Slippage ([slippage]%)

<img width="422" alt="Screen Shot 2022-07-12 at 10 47 26" src="https://user-images.githubusercontent.com/16665596/178449823-ec773998-337f-49d4-8543-b28ac834fdb2.png">

- can format 3. or not bother formatting 3
- make Valuation Impact Percentage red if > 5%

2022-07-13 03:56 UTC, chrisling-dev requested changes

2022-07-13 03:56 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: valuation === undefined ? undefined : `$${significantDigits(valuation)}`,
one thing I missed is that we should disable the button inside TransactionSummary and make it "loading" when `valuation === undefined`

2022-07-14 20:05 UTC, chrisling-dev commented
`Maximum Valuation After Slippage (1.5%)` should always be higher than Expected Valuation - after slippage, `amountOut` should be lower which means higher price hence higher valuation)

<img width="485" alt="Screenshot 2022-07-14 at 10 04 14 PM" src="https://user-images.githubusercontent.com/81092286/179073421-6d0bc3fb-73d6-4311-bbe3-32617b24d473.png">

2022-07-26 03:22 UTC, chrisling-dev requested changes

2022-07-26 03:22 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: `$${significantDigits(estimatedValution * (1 + slippage))}`,
This isn't quite right, we can't just apply slippage directly to estimatedValuation. Because of the relation between valuation and the actual long/short token price, 1.5% applied directly to estimated valuation could become a completely different number.

The math here is extremely complicated to explain IMO, I'll just send in an assisting PR shortly

2022-07-26 03:22 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: `$${significantDigits(estimatedValution * (1 + slippage))}`,
Actually, I'll just try my best to explain here:

If we use the formula here https://docs.prepo.io/concepts/markets#calculating-market-valuation-and-payouts to find the Long Token Price based on Valuation, we can get long token price of valuation with slippage applied directly to valuation (valuation taken at a trade size of 1000 usd):
0.01 + ((32077621228.958897 - 15000000000) / (45000000000 - 15000000000)) * (0.99 - 0.01) = **0.5678689601**

But if we apply slippage directly to token amount out (which is what slippage is about, the lowest amount out user is willing to accept):
const amountOutAfterSlippage = 1810.3374221679871 * 0.985 = 1783.1823608354673
const tokenPriceAfterSlippage = 1000 / amountOutAfterSlippage

We'll get **tokenPriceAfterSlippage = 0.5607951390521124** which is quite different from applying slippage directly to valuation.

2022-07-26 03:22 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +  const estimatedValution = valuation ?? 0
typo 
```suggestion
  const estimatedValuation = valuation ?? 0
```

2022-07-26 03:22 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: `$${significantDigits(estimatedValution * (1 + slippage))}`,
Also this would be wrong for shorting, when shorting, the valuation after slippage should be lower than "Expected Valuation", cause user will receive less short token, which means more expensive short token price, hence causing lower long token price, hence lower valuation after slippage

2022-07-26 03:22 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: `$${significantDigits(estimatedValution * (1 + slippage))}`,
Understand that this could be overwhelming, will send in a PR to assist shortly

2022-07-27 10:21 UTC, georgesmithishere commented on apps/frontend/core-dapp/src/features/trade/TradeTransactionSummary.tsx
> +      amount: `$${significantDigits(estimatedValution * (1 + slippage))}`,
thanks @chrisling-dev !

2022-08-02 07:59 UTC, chrisling-dev requested changes
Nice! Very clean solution! Just one last thing and this is good to go, It should be Minimum valuation after slippage when user is shorting, cause the valuation is going downwards

![Screenshot 2022-08-02 at 3 57 46 PM](https://user-images.githubusercontent.com/81092286/182323046-4f6531b4-6c0a-4cea-83d5-c7751463c042.png)

2022-08-03 08:32 UTC, chrisling-dev reviewed
LGTM but test seems to be failing

2022-08-03 09:33 UTC, chrisling-dev approved these changes

2022-08-03 10:31 UTC, merged