feat: bumped antd version, fixed depricated parts
prepo-io/prepo-monorepo pull request #203
Opened 2022-07-11 23:24 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=eae1b4be706349e28450ee06c09d161e

2022-07-11 23:40 UTC, r0x4xn commented
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-2867ne8vj-prepo.vercel.app'>https://react-boilerplate-2867ne8vj-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

2022-07-11 23:50 UTC, r0x4xn commented
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-83241svbf-prepo.vercel.app'>https://core-dapp-83241svbf-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

2022-07-14 19:52 UTC, chrisling-dev requested changes
Seems the color here is broken? 

<img width="165" alt="Screenshot 2022-07-14 at 9 52 23 PM" src="https://user-images.githubusercontent.com/81092286/179071366-0383127d-bf51-471a-a285-555e40b3e09d.png">

2022-07-14 19:52 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/Menu.tsx
> +`
Missing one closing curly bracket here
```suggestion
const keepBackgroundOnHover = css`
  .ant-dropdown-menu-item-active {
    background-color: ${({ theme }): string => theme.color.neutral10};;
    * {
      color: ${({ theme }): string => theme.color.neutral3};
      font-weight: ${({ theme }): number => theme.fontWeight.semiBold};
    }
    :hover {
      * {
        color: ${({ theme }): string => theme.color.primary};
        font-weight: ${({ theme }): number => theme.fontWeight.medium};
      }
    }
    }
`
```

2022-07-14 19:52 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/components/Menu.tsx
> +    }}
Alternative shorter and cleaner code IMO

```suggestion
    ${({ keepBackgroundColorOnHover }): FlattenInterpolation<ThemeProps<DefaultTheme>> => keepBackgroundColorOnHover ? keepBackgroundOnHover : hoverBackground
    }
```

2022-07-14 20:01 UTC, chrisling-dev requested changes

2022-07-27 02:22 UTC, chrisling-dev approved these changes

2022-07-27 08:59 UTC, merged