feat: init Staking ABI, stake implementation
prepo-io/prepo-monorepo pull request #233
Opened 2022-07-20 10:29 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=1dd09682d2914387a5e2384b30b35dba

2022-07-27 06:48 UTC, chrisling-dev requested changes
only few comments, other than that, my main concern is how do we hide these features (block the button) so users don't try this page and think it's broken, and how do we do that so that it doesn't block other PRs built on top of this?

2022-07-27 06:48 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/StakeStore.ts
>      if (this.currentStakingValue > balance) {
Maybe we could update this code to just do this below, and delete the `getBalance` method, this looks really redundant, it's reassigning the same thing to different variables twice while there's essentially no complexity at all, (token is "assigned" to getBalance, then getBalance is called to assign to `balance`, when we could've just used `tokenBalance` directly) understand that it's not changes from this PR, maybe good to have it fixed since it's relevant

Also the existing code is somewhat wrong, ppoTokenStore cannot be undefined, and `tokenBalance` is deprecated

```suggestion
    const { tokenBalanceFormat } = this.root.ppoTokenStore
    if (this.currentStakingValue > +(tokenBalanceFormat ?? 0)) {
```

2022-07-27 06:48 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/PPOStakingStore.ts
> +      })
Correct me if I'm wrong but we shouldn't need to wrap any state changes with runInAction until we some await occurred since the function is already configured as `action.bound`
```suggestion
        this.staking = true
        this.stakingHash = undefined
```

2022-07-27 06:48 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/StakeUnstakeLayout.tsx
>    const loading = delegate && !delegate.delegateAddress
loading should be true when it's staking

2022-07-27 06:48 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/StakeUnstakeLayout.tsx
> +    staking || loading || !(isStake ? isCurrentStakingValueValid : isCurrentUnstakingValueValid)
Then staking here can be removed since loading will be true when staking is true
```suggestion
    loading || !(isStake ? isCurrentStakingValueValid : isCurrentUnstakingValueValid)
```

2022-07-31 07:28 UTC, georgesmithishere commented on apps/frontend/core-dapp/src/features/ppo/stake/PPOStakingStore.ts
> +      })
I think you are correct, but have to investigate more 
https://github.com/mobxjs/mobx/blob/mobx4and5/docs/refguide/api.md#enforceactions
there's a cool rule - WDYT

2022-08-03 03:15 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/hooks/useFeatureFlag.ts
> +  }
👍

2022-08-03 04:04 UTC, chrisling-dev requested changes
LGTM after comments are addressed

2022-08-03 08:21 UTC, georgesmithishere commented on apps/frontend/core-dapp/src/features/ppo/stake/StakeStore.ts
> +      tokenBalanceRaw.gte(this.currentStakingValue)
thank you! this is great!

2022-08-09 10:39 UTC, chrisling-dev approved these changes
LGTM for mocking purposes

2022-08-09 10:45 UTC, merged