Feat/staking withdraw
prepo-io/prepo-monorepo pull request #249
Opened 2022-07-24 20:25 UTC by georgesmithishere

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=fe1c9e66fa304f78a507ae579312e6ad

2022-07-24 20:44 UTC, r0x4xn commented
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-kgg9pxaar-prepo.vercel.app'>https://core-dapp-kgg9pxaar-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

2022-08-10 09:25 UTC, chrisling-dev requested changes
LGTM after minor comments are resolved

2022-08-10 09:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/UnstakeStore.ts
> +    // gte = greater than or equal
remove this comment

2022-08-10 09:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/ppo/stake/UnstakeStore.ts
> +  }> => this.root.ppoStakingStore.withdraw(this.currentUnstakingValue, immediate)
Since there's no other logic in here we could just call this.root.ppoStakingStore.withdraw without wrapping it in another `withdraw` in this store right?

2022-08-10 11:49 UTC, chrisling-dev approved these changes
LGTM, let's merge after all tests pass

2022-08-10 12:50 UTC, merged