feat: acquisition royale buy rp
prepo-io/prepo-monorepo pull request #28
Opened 2022-04-27 10:50 UTC by chrisling-dev

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=1397d8ae2ac34198bbb256e097a6e92a

2022-04-27 10:59 UTC, jonezque commented on apps/frontend/acquisition-royale-home/src/features/mvp/trade/BuyRP.tsx
> +  const navigateToUniswap = (): void => {
Looks a little bit weird

2022-04-27 10:59 UTC, jonezque approved these changes

2022-04-27 13:28 UTC, r0x4xn requested changes

2022-04-30 10:42 UTC, chrisling-dev commented on apps/frontend/acquisition-royale-home/src/features/mvp/trade/BuyRP.tsx
> +    window.open('https://url.prepo.io/RP-MATIC')
Found out antd's button already handle turning Button with `href` to `a` tag! Just need to work on the style a bit

2022-05-02 07:43 UTC, r0x4xn approved these changes

2022-05-02 21:23 UTC, merged