feat: miniSales e2e test purchase and subsequent block
prepo-io/prepo-monorepo pull request #300
Opened 2022-08-10 16:08 UTC by Nilay27

* Adding end to end test for MiniSales for the scenarios:
   1. recipient is blocked/unblocked 
   2. transfers by the recipient after purchasing PPO.
* For clarity, I have written all the tests such that purchaser and recipient are different.
* I also had to split up `deployMiniSales` into `setupSignersAndMockTokens` + deployment so that we do not end up deploying MiniSales twice. As in the `deployMiniSales()` we deploy it with a `MockERC20` token whereas for E2E testing we need actual `PPO` token.

2022-08-11 00:25 UTC, ramenforbreakfast requested changes
Edit: don't think this necessarily warrants a requested changes anymore since I now understand how unpermissioned and permissioned tests are organized.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +  const setupSignersAndMockTokens = async (): Promise<void> => {
Good call splitting this out.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    const getSignersAndMockTokenForEndToEndStack = async (): Promise<void> => {
```suggestion
    const getSignersAndMockTokenForEndToEndTest = async (): Promise<void> => {
```
Technically these users are not being setup for the stack, but for end to end testing.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> -    let contractSaleTokenBalance: BigNumber
For other reviewers information, this moved now because more than one `describe` block now needs access to these variables.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      // Setup allow list purchase hook
```suggestion
      // Setup AllowlistPurchaseHook
```
You are referring directly to the contract that will be used, so capitalization according to the contract name should be used.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      // Setup Source allow list
```suggestion
      // Setup source allowlist
```

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      // Setup Destination allow list
```suggestion
      // Setup destination allowlist
```

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      // Setup Blocklist
```suggestion
      // Setup blocklist
```
These are not contract names, so no need to use capital letters.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      await allowlistPurchaseHook.connect(owner).setAllowlist(purchaseAllowlist.address)
Where is the `allowlistPurchaseHook` connected to the `MiniSales` contract? Right now this is essentially testing a MiniSales with no purchase permissions enabled.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      await allowlistPurchaseHook.connect(owner).setAllowlist(purchaseAllowlist.address)
Edit: I see PR 302 is when a permissioned sale test begins.

To avoid confusion, I would move setup of `purchaseAllowlist` and `allowlistPurchaseHook` out of this `describe` block.

2022-08-11 00:25 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    beforeEach(async () => {
```suggestion
    beforeEach(async () => {
```
I would put this section and the section in PR 301 under their own parent `describe` block to make it clear that these are tests for unpermissioned sales. Describe nesting becomes more important when we have so many different access controls we need to test together.

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    it('reverts purchase if recipient blocked', async () => {
```suggestion
    it('reverts purchase if recipient blocked by PPO', async () => {
```
After reading PR 302, I realize your organization scheme is essentially the same as previous PRs where you write the PPO access control conditions (i.e. recipient blocked), but later on will have `if sale permissioned...` nested, where MiniSales specific access control conditions are listed.

This is fine, but it can get confusing with different access controls, lets be specific in this test suite about which "contract stack"'s access controls we are referring to.

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    it('purchases if recipient not blocked', async () => {
```suggestion
    it('purchases if recipient not blocked by PPO', async () => {
```

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    describe('if user purchases, but is subsequently blocked', () => {
```suggestion
    describe('if user purchases, but is subsequently blocked by PPO', () => {
```

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      it('reverts if user transfers purchased PPO to blocked recipient', async () => {
```suggestion
      it('reverts if user transfers purchased PPO to recipient blocked by PPO', async () => {
```

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      it('reverts if user transfers purchased PPO to not allowed destination', async () => {
```suggestion
      it('reverts if user transfers purchased PPO to not allowed PPO destination', async () => {
```

2022-08-11 00:37 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +      it('reverts if user transfers purchased PPO to allowed destination', async () => {
```suggestion
      it('reverts if user transfers purchased PPO to allowed PPO destination', async () => {
```

2022-08-11 00:39 UTC, ramenforbreakfast submitted a review, later dismissed

2022-08-11 01:41 UTC, ramenforbreakfast commented
I've addressed the nits I made to speed things up, just resolve them to confirm you are aware of the changes I suggested for later PRs.

2022-08-11 09:02 UTC, Nilay27 commented
As per the discussion with @ramenforbreakfast , I have modified the tests such that instead of having just one separate `permissioned sale` test at the end  covering allowed and not allowed recipient, we should have permissioned sale cases included in each of the three scenarios. i.e
1. `if user purchases, but is subsequently blocked by PPO`
2. `if user purchases and is not allowed source`
3.  `if user purchases and is allowed source`

This PR contains test case for scenario 1. Scenarios 2 and 3 will be covered in subsequent PRs.

2022-08-12 00:07 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/MiniSales.test.ts
> +    const setupUnpermissionedEndToEndStack = async (): Promise<void> => {
```suggestion
    const setupEndToEndStack = async (): Promise<void> => {
```
No need for this, maybe just add a comment saying sale permissions are setup in a separate function `setupPermissionSale` rather than making this function name unnecessarily long.

2022-08-16 04:43 UTC, ramenforbreakfast commented
@Nilay27 , please rebase this and fix conflicts, also include the changes I made in PR #293 if they apply.

2022-10-18 23:55 UTC, ramenforbreakfast commented
Closing due to irrelevance, will need to be heavily modified anyway if we want to include them because of how old this PR is.

2022-10-18 23:55 UTC, closed without merging