test: adding tests for transferFromWithPermit in PPO
prepo-io/prepo-monorepo pull request #324
Opened 2022-08-16 13:20 UTC by Nilay27

* Adding test for `transferFromWithPermit()`. 
* Although this PR is big in terms of numbers of lines, but that is mostly because of following multiline calls :
```
await getPermitSignature(
        user1,
        ppo,
        user2.address,
        user1PPOBalanceBefore,
        deadline
      )

and 

await ppo
        .connect(spender)
        .transferFromWithPermit(
          user1.address,
          user2.address,
          user1PPOBalanceBefore,
          deadline,
          v,
          r,
          s
        )
```

Otherwise, it is not dissimilar to tests for usual transfer/transferFrom methods with a few added scenarios. Hence I decided to submit it in one go.

2022-08-16 21:24 UTC, ramenforbreakfast requested changes
I think this test suite needs some more changes before I can approve.

2022-08-16 21:24 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/PPO.test.ts
> +  let spender: SignerWithAddress
I think better to move this to `transferFromWithPermit`, and instead of having a unique signer as `spender`, let's just set `spender = user2` or something.

2022-08-16 21:24 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/PPO.test.ts
> +            user2.address,
```suggestion
            user2.address,
```
This is a bad test because you've generating a permit signature for `spender.address` to spend, yet passed in `user2.address`, so it would fail even with a good deadline.

This is why i keep emphasizing you need to write your tests in a way that makes it clear what inputs are changing if your tests change inputs alot, especially with a function that has this many parameters and ones that aren't obvious. Like `timeAfterDeadlineExpiration` is fine because its very clear that this time is past the deadline since we can see it is `deadline + BLOCK_DURATION_IN_SECONDS`, so there is also no need for an expect.

It's harder with an input like an account because you are juggling 3 accounts around all the time.

2022-08-16 21:24 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/PPO.test.ts
> +    it('transfers to recipient if recipient is not spender', async () => {
This is related to PR #323, but this is a perfect example of why it makes no sense. The recipient _is_ the spender. I am not sure in what scenario you would write a signature to approve a spend and then send tokens to someone else?

If you agree with this point, lets remove these `if recipient not spender` and `if recipient is spender` cases and leave it with just the `transfers to recipient...` cases.

2022-08-16 21:24 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/PPO.test.ts
> +    it('emits transfer if amount = 0 and recipient is spender', async () => {
```suggestion
    it('emits transfer if amount = 0', async () => {
```
Can remove the other test case if no security concerns with PR #323 suggestion. Please do this for other cases.

2022-08-17 03:26 UTC, Nilay27 commented on apps/smart-contracts/token/test/PPO.test.ts
> +            user2.address,
I don't see how you concluded that the test will fail even with a good deadline when it doesn't (the test does not revert if you pass in `deadline` to `setNextTimestamp`. 

As per the current implementation, a user (`user1`) approves an account to spend its tokens and then the approved account can transfer the tokens to a recipient (other than user1 also), here the approved account is `spender` hence the spender can now transfer those tokens to another user (`user2`)

2022-08-17 03:53 UTC, ramenforbreakfast commented on apps/smart-contracts/token/test/PPO.test.ts
> +            user2.address,
Ah yes this is my confusion, I forgot that the `spender` can send to another address, this is my bad.

2022-08-17 03:54 UTC, ramenforbreakfast approved these changes

2022-08-17 03:54 UTC, ramenforbreakfast commented
I for some reason had a brain fart and thought the spender and recipient had to be the same for `transferFrom`, I have dismissed my comments and have approved the test suite.

2022-08-18 08:19 UTC, XavierEkkel approved these changes
LGTM after comments

2022-08-18 08:19 UTC, XavierEkkel commented on apps/smart-contracts/token/test/PPO.test.ts
> +    it('reverts if invalid signature', async () => {
i think this should be split into:
- `reverts if from address different from signature`
- `reverts if to address different from signature`
- `reverts if deadline different from signature`
- `reverts if invalid v`
- `reverts if invalid r`
- `reverts if invalid s`

2022-08-19 16:31 UTC, merged