Feat/portfolio filter
prepo-io/prepo-monorepo pull request #435
Opened 2022-10-11 10:36 UTC by georgesmithishere

https://www.notion.so/prepo/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=0b2cd82c9a6c489fa28e98815c870a1a&pm=s

2022-10-12 07:47 UTC, chrisling-dev requested changes
Overall the behaviour is okay except for 1 thing:

- The filter shouldn't be applied until they click "Confirm", currently if I select a tx type for example, without clicking "Confirm" it already applies in the background which feels very weird. 
 
The solution should be that, on the filter modal (or wherever the UI is), we keep track of a local state, and these local states only get applied to PortfolioStore when confirm is clicked. And if I close or cancel the filter, it should reset to the states on PortfolioStore

2022-10-12 07:47 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/graphs/CoreGraphStore.ts
> +export type HistoryEventFilter = {
for consistency purpose could we rename this to `HistoricalEventsFilter`
```suggestion
export type HistoricalEventsFilter = {
```

2022-10-12 07:47 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/graphs/CoreGraphStore.ts
> +  historicalEvents = (filter: HistoryEventFilter): HistoricalEvents | undefined =>
```suggestion
  historicalEvents = (filter: HistoricalEventsFilter): HistoricalEvents | undefined =>
```

2022-10-12 08:52 UTC, georgesmithishere commented
> Overall the behaviour is okay except for 1 thing:
> 
> * The filter shouldn't be applied until they click "Confirm", currently if I select a tx type for example, without clicking "Confirm" it already applies in the background which feels very weird.
> 
> The solution should be that, on the filter modal (or wherever the UI is), we keep track of a local state, and these local states only get applied to PortfolioStore when confirm is clicked. And if I close or cancel the filter, it should reset to the states on PortfolioStore

I totally agree with you, and I showed that behavior at sync, created separate ticket for it

2022-10-20 23:09 UTC, chrisling-dev approved these changes
LGTM

2022-10-20 23:09 UTC, merged