feat: setters and getters for nft access logic
prepo-io/prepo-monorepo pull request #576
Opened 2022-11-28 14:19 UTC by davidprepo

2022-11-28 18:58 UTC, ramenforbreakfast requested changes
Test suite needs some work, also since these setters are not as straightforward as typical setters, please split this out into two additional PRs, one with `setCollections` and one with `removeCollections`

1. setRequiredScore + getRequiredScore
2. setCollectionScores+getCollectionScore
3. removeCollections (not a setter or a getter)

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/DepositHook.sol
> +  uint256 requiredScore;
```suggestion
  uint256 private requiredScore;
```

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/DepositHook.sol
>    bool public override depositsAllowed;
```suggestion
  bool public depositsAllowed;
```
Seems like this got merged in when you were addressing underscores, this is incorrect and should be removed.

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/DepositHook.sol
> +  EnumerableMap.AddressToUintMap private nftCollectionToScore;
```suggestion
  EnumerableMap.AddressToUintMap private collectionToScore;
```
Since we don't call it nftCollection anywhere else, lets keep it consistent.

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('sets score for two collections', async () => {
```suggestion
    it('sets scores for multiple collections', async () => {
```

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +
add a testcase `reverts if multiple collections added and one has a 0 score`
for testing if multiple collections are added, 1 with a non-zero score and 1 with a 0 score.

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('removes two collections', async () => {
```suggestion
    it('removes multiple collections', async () => {
```

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +      expect(await depositHook.getCollectionScore(testERC721.address)).to.eq(1)
```suggestion
      expect(await depositHook.getCollectionScore(secondERC721.address)).to.eq(0)
```

No need to add the first collection, can just expect that it doesnt exist at the beginning, and subsequently verify that it still doesn't exist.

Since you didn't add an idempotence test here, i would actually just replace this with an idempotence test. So first add the collection, then remove it, then remove it again.

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +      expect(await depositHook.getCollectionScore(testERC721.address)).to.eq(1)
```suggestion
      expect(await depositHook.getCollectionScore(secondERC721.address)).to.eq(0)
```

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +
Missing idempotence test.

2022-11-28 18:58 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('emits CollectionScoresChange', async () => {
This test doesn't really test anything? You should have collections that exist prior to removing them?

2022-11-28 21:51 UTC, davidprepo commented
Removed collection logic

2022-11-28 22:02 UTC, ramenforbreakfast approved these changes
LGTM, please move testcases to other PR rather than including them here.

2022-11-28 22:02 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('reverts if not role holder', async () => {
Take these tests out and move them to their respective PRs.

2022-11-28 22:02 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +  describe('# removeCollections', () => {
```suggestion
  describe('# removeCollections', () => {
```
This test block as well.

2022-11-28 22:02 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +
Remember to add this testcase in for the next PR.

2022-11-28 22:54 UTC, ramenforbreakfast commented
@davidprepo in the future, please also put in the PR description the PRs this is linked to, e.g. PR #583, 584

2022-11-29 12:15 UTC, davidprepo commented
All comments are fixed, this has been split into sub PRs.

2022-11-29 17:45 UTC, ramenforbreakfast approved these changes
LGTM besides minor nits.

2022-11-29 17:45 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/DepositHook.sol
> +  INFTAccessHook
Put these above `SafeAccessControlEnumerable`, group together interfaces

2022-11-29 17:45 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('sets required score > 0', async () => {
```suggestion
    it('sets to > 0', async () => {
```
No need to specify the name since its implied for simple testcases like this.

2022-11-29 17:45 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +    it('sets required score to 0', async () => {
```suggestion
    it('sets to 0', async () => {
```

2022-11-29 17:45 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +      expect(await depositHook.getRequiredScore()).to.eq(1)
```suggestion
      expect(await depositHook.getRequiredScore()).to.not.eq(0)
```
Should reflect the name of the testcase.

2022-11-29 17:45 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +      expect(await depositHook.getRequiredScore()).to.eq(0)
```suggestion
      expect(await depositHook.getRequiredScore()).to.not.be.gt(0)
```
Should reflect name of testcase.

2022-11-29 22:10 UTC, XavierEkkel approved these changes
LGTM after comment

2022-11-29 22:10 UTC, XavierEkkel commented on apps/smart-contracts/core/test/DepositHook.test.ts
> +      expect(await depositHook.getRequiredScore()).to.eq(0)
same for the expect statement (`to.be.gt(0)`), and same for the other tests below

2022-11-30 11:03 UTC, merged