feat: skeleton for token sender
prepo-io/prepo-monorepo pull request #599
Opened 2022-11-29 12:13 UTC by davidprepo

https://github.com/prepo-io/prepo-monorepo/pull/578

2022-11-30 03:07 UTC, ramenforbreakfast requested changes
I think the skeleton should contain at least the constructor and the variables. Also remember to use the new convention where internal variables are `_` and external ones/parameters are not.

2022-11-30 12:46 UTC, XavierEkkel approved these changes
LGTM after nits

2022-11-30 12:46 UTC, XavierEkkel commented on apps/smart-contracts/core/test/TokenSender.test.ts
> +    it('has output token set', async () => {
nit:
```suggestion
    it('sets output token from constructor', async () => {
```

2022-11-30 12:46 UTC, XavierEkkel commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +  uint256 private immutable _outputTokenDecimalsFactor;
nit: move immutables below non-immutable variables, separated by one empty line before

2022-11-30 12:46 UTC, XavierEkkel commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +  function send(address _recipient, uint256 _unconvertedAmount)
nit:
```suggestion
  function send(address recipient, uint256 unconvertedAmount)
```

2022-12-01 19:19 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +    _outputToken = outputToken;
```suggestion
    _outputToken = outputToken;
```
Nice, I didn't know it would implicitly convert? (Since you are setting an `IERC20` to a `IERC20Metadata`)

2022-12-01 22:20 UTC, davidprepo commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +    _outputToken = outputToken;
Yeah, IERC20Metadata inherits from IERC20 so it's directly castable.

2022-12-02 11:00 UTC, merged