feat: shared: Remove SafeOwnable from WithdrawERC20 and move access control logic to inheriting contracts
prepo-io/prepo-monorepo pull request #693
Opened 2022-12-15 13:23 UTC by davidprepo

2022-12-16 04:33 UTC, ramenforbreakfast submitted a review, later dismissed

2022-12-16 04:33 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +    keccak256("TokenSender_withdrawERC20(address[])");
```suggestion
  bytes32 public constant WITHDRAW_ERC20_ROLE =
    keccak256("withdrawERC20");
```
I am in support of keeping the same role for both `withdrawERC20` functions, can change the other role signature later.

2022-12-16 04:33 UTC, ramenforbreakfast commented on packages/prepo-shared-contracts/test/SafeAccessControlEnumerableUpgradeable.test.ts
> +      await expect(safeAccessControlEnumerable.connect(user1).acceptRoleAdmin(roleB)).revertedWith(
This is just because we forgot to run the linter when we removed `to.be.revertedWith` calls everywhere or something? Nothing has changed here right?

2022-12-16 20:35 UTC, davidprepo commented on packages/prepo-shared-contracts/test/SafeAccessControlEnumerableUpgradeable.test.ts
> +      await expect(safeAccessControlEnumerable.connect(user1).acceptRoleAdmin(roleB)).revertedWith(
Yes correct

2022-12-17 03:53 UTC, ramenforbreakfast requested changes

2022-12-17 03:53 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/TokenSender.sol
> +    super.withdrawERC20(erc20Tokens, amounts);
I do not think this will work, `withdrawERC20` sends to `msg.sender`. In this case, this is an internal call, so it would send to the contract itself.

I think the appropriate fix here would be to change `withdrawERC20` to accept a `recipient`, and leave it up to the inheriting contract to decide whether to lock sending to `msg.sender` or not.

2022-12-17 03:53 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/TokenSender.test.ts
>      })
Where are the tests to ensure it is callable?

2022-12-17 04:06 UTC, ramenforbreakfast approved these changes

2022-12-19 13:29 UTC, XavierEkkel approved these changes
LGTM but should also change to `SafePausable` for many of these contracts later

2022-12-19 13:41 UTC, XavierEkkel commented on apps/smart-contracts/core/test/TokenSender.test.ts
> +  describe.only('# withdrawERC20', () => {
```suggestion
  describe('# withdrawERC20', () => {
```

2022-12-19 14:16 UTC, merged