refactor: core: Collateral test using Snapshotter
prepo-io/prepo-monorepo pull request #697
Opened 2022-12-16 22:09 UTC by davidprepo

2022-12-16 22:12 UTC, davidprepo commented on apps/smart-contracts/core/test/Collateral.test.ts
> +      after(async () => {
After this block we must redo the setup as local variables in the test can become mismatched with the decimal back and forth.

2022-12-20 03:10 UTC, ramenforbreakfast approved these changes
LGTM, needs rebasing however, its using the old snapshot naming. Also question about unnamed snapshot contexts.

2022-12-20 03:10 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/Collateral.test.ts
> +    snapshotter.usesCustomSnapshot()
```suggestion
    snapshotter.usesCustomSnapshot()
```
Are we not naming these anymore? i.e. `Collateral-setManager`, this is being done in 674 no?

2022-12-22 19:10 UTC, XavierEkkel requested changes
please split up this PR

2023-01-08 01:58 UTC, ramenforbreakfast commented
Closing due to deprioritization.

2023-01-08 01:58 UTC, closed without merging