refactor: using properly typed mocks and fakes
prepo-io/prepo-monorepo pull request #699
Opened 2022-12-17 14:17 UTC by davidprepo

2022-12-18 06:14 UTC, ramenforbreakfast requested changes
Needs some work regarding changing the type of generic function parameters and should just add typed returns for fixtures for all fixtures, not just ones that affect current tests

2022-12-18 06:14 UTC, ramenforbreakfast commented on packages/prepo-hardhat/src/smart-contracts-utils.ts
> +    (token as any).name(),
Ok so after some research and experimentation, I think the best solution will be to remove these `as any` casts and just use `SmockContractBase<Contract>` instead of `SmockContractBase<BaseContract>` for functions that take in a generic contract.

2022-12-20 04:35 UTC, ramenforbreakfast approved these changes
LGTM besides a few relatively minor changes, I've checked on my end that the tests work.

Please in the future when we have an invasive change to not include extra refactoring unless absolutely necessary.

2022-12-20 04:35 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/utils.ts
> +import { PermitStruct } from '../types/generated/IDepositTradeHelper'
Undo changes you made to struct import references as discussed in discord.

2022-12-20 21:57 UTC, ramenforbreakfast reviewed
I was going to nit on more changes to `fake` prefixing and `mock` prefixing on variables, but I think this hsould just happen in a later PR instead to reduce the complexity of this change.

2022-12-20 21:57 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/TokenSender.test.ts
>      allowlist = await fakeAccountListFixture()
```suggestion
    fakePriceOracle = await fakeTestUintValueFixture()
    fakeAllowlist = await fakeAccountListFixture()
```

2022-12-21 08:01 UTC, XavierEkkel approved these changes
LGTM after comments

2022-12-21 08:01 UTC, XavierEkkel commented on apps/smart-contracts/core/test/Collateral.test.ts
> +      const contractBT = await baseToken.balanceOf(collateral.address)
this is already declared above

2022-12-22 11:02 UTC, davidprepo commented on packages/prepo-hardhat/src/smart-contracts-utils.ts
> +// todo: Add type safety for token
This should take a type which we know will implement the permit functionality rather than taking a generic `Contract` type.

2022-12-22 11:13 UTC, merged