feat: ability to select network
prepo-io/prepo-monorepo pull request #83
Opened 2022-05-26 19:52 UTC by jonezque

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=35dcf02f76284d8e8efe0b67f7a04234&p=816f1874d8904de6a0da1eb1f4ce3e80

I think Figma design is outdated, network window is in graveyard,
added ability to change current network, tested with arbitrum testnetwork

2022-05-31 10:03 UTC, r0x4xn commented
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-cei97s2kb-prepo.vercel.app'>https://core-dapp-cei97s2kb-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

2022-05-31 10:54 UTC, r0x4xn requested changes

2022-05-31 10:54 UTC, r0x4xn commented on apps/frontend/core-dapp/src/components/NetworkDropdown.tsx
> +  { iconName: 'arbitrum', name: 'Arbitrum', supported: false, type: 'arbitrum', chainId: -1 },
What is `-1` representing here? Can we add it to a constant to be more explicit?

2022-05-31 10:54 UTC, r0x4xn commented on apps/frontend/core-dapp/src/components/NetworkDropdown.tsx
> +  const selectNetowrk = (id: ChainId): void => {
typo `selectNetwork`

2022-05-31 10:59 UTC, jonezque commented on apps/frontend/core-dapp/src/components/NetworkDropdown.tsx
> +  { iconName: 'arbitrum', name: 'Arbitrum', supported: false, type: 'arbitrum', chainId: -1 },
we don't yet support Arbitrum,
decided to provide non-existing ID(UI should be blocked for coming soon networks but still)

2022-05-31 11:00 UTC, jonezque commented on apps/frontend/core-dapp/src/components/NetworkDropdown.tsx
> +  const selectNetowrk = (id: ChainId): void => {
thanks

2022-06-01 12:29 UTC, r0x4xn approved these changes

2022-06-01 20:46 UTC, merged