feat: add `/portfolio-next` page with the next "Positions" component
prepo-io/prepo-monorepo pull request #841
Opened 2023-02-06 16:05 UTC by MeLlamoPablo

This PR adds a new `/portfolio-next` page with the new design's base layout, and introduces a `PositionsNext` component with the new design. We can keep iterating on the `-next` page and eventually replace `/portfolio` with `/portfolio-next`.

For ease of review, you can skip the first three commits, which just duplicate code.

https://user-images.githubusercontent.com/11708035/217013107-9b1865a6-dd11-4284-9fa4-ae571d28d92b.mp4

### What's not included

* The correct skeleton loader for the Positions tab
* The History tab must be redesigned too, along with the filters
* The Portfolio Value component must be redesigned

### Open questions

* I haven't included "Base value" and "Base price" on the tooltip because I can't find them on the current `PositionEntity` object. What do these values refer to?
  * What is the cost basis?

# FE PR Checklist

- [X] Self-reviewed each line of code, preempted questions about logic or decisions
- [X] Noted any intentional deviations from design
- [X] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [X] Tested on supported device sizes
    - [X] iPhone 12 Pro
    - [X] iPad Air
    - [X] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [X] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [X] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [X] (if browser specific logic) Tested on Brave, Firefox, Safari
- [X] (if styling) Tested Light/Dark mode

2023-02-07 05:25 UTC, chrisling-dev requested changes
Nice work, some minor comments

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PositionsAndHistoryNext.tsx
> +
Add same padding as figma (note that we have to add in .ant-tabs-nav-wrap to prevent ink bar from overflow-hidden

```suggestion

    .ant-tabs-nav-wrap {
      padding: ${spacingIncrement(16)};
      padding-bottom: ${spacingIncrement(8)};
    }

```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PositionsAndHistoryNext.tsx
> +      padding: ${spacingIncrement(8)} 0;
Then remove padding here:

```suggestion
      padding: 0;
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PositionsAndHistoryNext.tsx
> +      padding: 0 ${spacingIncrement(24)};
and remove padding here

```suggestion
      padding: 0;
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PositionsAndHistoryNext.tsx
> +    }
Offset 4px from tab item

```suggestion
    .ant-tabs-ink-bar {
      border-radius: 1px 1px 0 0;
      height: ${spacingIncrement(4)};
      bottom: ${spacingIncrement(-4)};
    }
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +  onIncrementPosition: () => void
Can omit "Position" because this is Prop is for Position so it's implied

Also use verb for better naming convention (e.g. html's onChange, onDrag, onFocus)

```suggestion
  onDecrease: () => void
  onIncrease: () => void
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +          // TODO redirect to the proper URL
👍 can create a ticket and do this in a separate PR so this PR is UI focus and the other can be the logic

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +      {selectedPosition && <ClosePositionSummary position={selectedPosition} />}
and can remove this, clicking minus will just bring user to /trade page. I've added details in the ticket, feel free to move those details to a new ticket

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +        <PlusButton onClick={onDecrementPosition}>
Maybe rename this to "IconButton" since it's technically not a Plus here?

```suggestion
        <IconButton onClick={onDecrease}>
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +              <p>{toUsd(price)}</p>
Nice! But I think we don't need to show total value and price since total value is show next to the icon and users won't directly be aware of token price, so we can remove these two and just show profit for now

```suggestion
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +  transition: opacity 200ms;
Nice touch but prefer to have no animation so the UI feedback looks instant to user

```suggestion
```

2023-02-07 05:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +const Position: React.FC<PositionProps> = ({
Consider moving this to a separate Position.tsx file since it's getting kinda big

2023-02-07 08:03 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/position/PositionLabel.tsx
> +          `};
384fc3b1221707f6479f3f2415c0ef828c0f3405 - however I had to add a check so that `positionType` is not `liquidity`

2023-02-07 08:08 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/portfolio/PositionsAndHistoryNext.tsx
> +    }
I'm not following why do we need this. I made the changes on 409cd2b0425ec87622d58809b51c2b3eba4d8dd9 and it looks fine to me:

![Screenshot 2023-02-07 at 09 04 17](https://user-images.githubusercontent.com/11708035/217186969-00276d64-6ff1-4725-b3d7-af87231fb318.png)

Btw, off topic, but I subscribe to the opinion that [shadows should be dark on dark mode](https://twitter.com/danqing_liu/status/1579536100980592641), what do you think?

2023-02-07 08:12 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +              <p>{toUsd(price)}</p>
The percentage does seem a bit redundant this way, but we can always change it later

2023-02-07 08:22 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/position/PositionsNext.tsx
> +          // TODO redirect to the proper URL
It's a small change, so I've done it here

2023-02-08 03:56 UTC, chrisling-dev requested changes
LGTM after comments

2023-02-08 03:56 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioNext.tsx
> +              {/* eslint-disable-next-line react/jsx-props-no-spreading */}
```suggestion
```

2023-02-08 03:56 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioNext.tsx
> +              {/* eslint-disable-next-line react/jsx-props-no-spreading */}
```suggestion
```

2023-02-08 04:01 UTC, chrisling-dev requested changes

2023-02-08 04:01 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +          placement="right"
can remove this too

2023-02-08 08:39 UTC, chrisling-dev approved these changes
LGTM

2023-02-08 11:57 UTC, MeLlamoPablo commented
@XavierEkkel if you could prioritize the review of this one, it would be helpful as it is blocking others. Feel free to merge if it looks good :)

2023-02-08 16:39 UTC, XavierEkkel approved these changes
LGTM from UI perspective after:

- removing transition animation between Position+History tabs
- ensuring 'trade now' button goes to `/trade` not `/markets`

2023-02-08 18:08 UTC, merged