feat: add better skeletons on the positions list on `/portfolio-next`
prepo-io/prepo-monorepo pull request #847
Opened 2023-02-07 12:54 UTC by MeLlamoPablo

Blocked by #841

2023-02-08 08:42 UTC, chrisling-dev requested changes
LGTM after rebasing feat/portfolio-next-layout and remove the goToTrade function

2023-02-08 08:45 UTC, chrisling-dev requested changes

2023-02-08 08:45 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +import Skeleton from 'react-loading-skeleton'
oh wait let's use the Skeleton component we've built that would consider for dark theme, it's under `src/components/Skeleton.tsx`

2023-02-08 13:35 UTC, chrisling-dev requested changes
LGTM after nit

2023-02-08 13:35 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +    <Skeleton circle height={46} width={46} />
To match the actual logo size

```suggestion
    <Skeleton circle height={48} width={48} />
```

2023-02-09 06:22 UTC, XavierEkkel approved these changes
LGTM from UI perspective

2023-02-09 11:55 UTC, chrisling-dev approved these changes
LGTM!

2023-02-09 12:09 UTC, merged