feat/portfolio history
prepo-io/prepo-monorepo pull request #852
Opened 2023-02-08 11:52 UTC by MeLlamoPablo

**Blocked by #841 and #848 - not meant to be reviewed**

----

# FE PR Checklist

- [ ] Self-reviewed each line of code, preempted questions about logic or decisions
- [ ] Noted any intentional deviations from design
- [ ] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [ ] Tested on supported device sizes
    - [ ] iPhone 12 Pro
    - [ ] iPad Air
    - [ ] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [ ] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [ ] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [ ] (if browser specific logic) Tested on Brave, Firefox, Safari
- [ ] (if styling) Tested Light/Dark mode

2023-02-10 03:15 UTC, chrisling-dev requested changes

2023-02-10 03:15 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +          {eventType && <PositionLabel positionType={eventType} />}
Can update this component's font-size to 14px to match design, the `PositionLabel` is only used once and that use case will be removed after your changes anyways

2023-02-10 03:15 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +            />
I think can just use the html nearr entity to make it simpler and more readable, wdyt?

Ref: https://www.w3schools.com/charsets/ref_html_entities_n.asp

```suggestion
            {event} &#x02197;
```

2023-02-10 03:25 UTC, chrisling-dev requested changes
Can simplify redirect url, marketId won't ever be undefined for Opened/Closed event, even if it's undefined I think we can still redirect for action and direction

2023-02-10 03:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +  if (event === 'Withdrawn') nameRedirectUrl = '/portfolio/withdraw'
I guess there isn't a case where nameRedirectUrl would be undefined + since event won't change for each transaction, we can do this in a memo so the logic doesn't get computed again:

```suggestion
  const nameRedirectUrl = useMemo(() => {
    switch (event) {
      case 'Deposited':
        return '/portfolio/deposit'
      case 'Withdrawn':
        return '/portfolio/withdraw'
      default:
        return {
          pathname: '/trade',
          query: { action: event === 'Opened' ? 'open' : 'close', direction: eventType, marketId },
        }
    }
  }, [event, eventType, marketId])
```

2023-02-10 03:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +
Then this can be simplified

```suggestion
          <Link href={nameRedirectUrl} passHref>
            <PositionName as="a">{name}</PositionName>
          </Link>
```

2023-02-10 09:39 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/utils/date-utils.ts
> +  format(ms, isCurrentYear(ms) ? DATE_TIME_FORMAT : DATE_FORMAT_SHORTEN_MONTH)
Reverted to the old format (it doesn't match the design tho)

IMO the tooltip approach is overkill. I think we should aim for simplicity in this case. Also, we would need to add a ℹ️ icon, which adds visual clutter, or the feature wouldn't be discoverable on mobile.

I think that if the user wants to know the time, they can just go to Etherscan.

2023-02-10 09:48 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +            />
Nice!

2023-02-10 09:58 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +  if (event === 'Withdrawn') nameRedirectUrl = '/portfolio/withdraw'
I agree with `useMemo` because it looks cleaner (it's its own function, so we can use return to alter the control flow), but not for the performance optimization. I think that would be premature optimization.

This is one of the examples why Kotlin is my favorite language, control statements are expressions so you can assign them to a variable 😆 

```kt
val nameRedirectUrl = when (event) {
  "Deposited" -> "/portfolio/deposit"
  "Withdrawn" -> "/portfolio/withdrawn"
  else -> // the location object
}
```

2023-02-10 10:30 UTC, chrisling-dev requested changes
LGTM after nits

2023-02-10 10:30 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/PositionLabel.tsx
> +  font-size: ${({ theme }): string => theme.fontSize.md};
Should this be sm (14px) instead of md?
```suggestion
  font-size: ${({ theme }): string => theme.fontSize.sm};
```

2023-02-10 10:30 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +            <PositionName as="a">{name}</PositionName>
Could we make it such that when hovering on it, the name turns `primary` purple instead of blue? Same for EventLink

2023-02-10 10:32 UTC, chrisling-dev requested changes

2023-02-10 10:32 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +`
ohh also add white-space: nowrap to this

```suggestion
const EventLink = styled.a<{ $event: string }>`
  align-items: center;
  background: ${({ $event, theme }): string =>
    theme.color[transactionTypeColors[$event].backgroundColor]};
  border-radius: ${spacingIncrement(8)};
  color: ${({ $event, theme }): string => theme.color[transactionTypeColors[$event].color]};
  display: flex;
  padding: ${spacingIncrement(2)} ${spacingIncrement(8)};
  white-space: nowrap;
`
```

2023-02-13 05:12 UTC, chrisling-dev requested changes
LGTM after comments

2023-02-13 05:12 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +        <Link href={`${NETWORKS[network.name].blockExplorer}/tx/${transactionHash}`} passHref>
There's a function from Web3Store that lets you do this:
```suggestion
        <Link href={web3Store.getBlockExplorerUrl(transactionHash)} passHref>
```

2023-02-13 05:12 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/History.tsx
> +export const buttonColors: { [key: string]: RecordButtonColors } = {
Should we duplicate this over instead of exporting since we will likely remove this file later when `/portfolio-next` is done?

2023-02-13 05:12 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +export const PositionName = styled.p`
ditto about duplicating

2023-02-13 05:12 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/history/HistoryTransaction.tsx
> +        return '/portfolio/withdraw'
We have a `Routes` enum that we can use here, you can import it from `/src/lib/routes`

```suggestion
      case 'Deposited':
        return Routes.Deposit
      case 'Withdrawn':
        return Routes.Withdraw
```

2023-02-13 14:02 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/history/History.tsx
> +export const buttonColors: { [key: string]: RecordButtonColors } = {
Yeah I'm aware of that. I simply exported it to not introduce unnecessary lines of code in this PR

2023-02-13 14:03 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +export const PositionName = styled.p`
Actually this is from the new Position component. We are just using the same styles on the new Position component and the new History component.

2023-02-14 07:15 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/position/Position.tsx
> +export const PositionName = styled.p`
ahh gotcha

2023-02-14 07:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/utils/date-utils.ts
> +  format(ms, isCurrentYear(ms) ? DATE_TIME_FORMAT : DATE_FORMAT_SHORTEN_MONTH)
could we have another formatting function then to make it match the design? it should just show [date] [month] [hour]:[sec]

2023-02-14 07:26 UTC, chrisling-dev commented
LGTM after the date is resolved, or feel free to create another ticket to do it separately

2023-02-14 10:13 UTC, chrisling-dev approved these changes
LGTM

2023-02-14 10:34 UTC, MeLlamoPablo commented
@XavierEkkel you commented but didn't approve or request changes, is this good to merge?

2023-02-15 08:42 UTC, merged