feat:core: allow market to burn tokens without approval
prepo-io/prepo-monorepo pull request #856
Opened 2023-02-08 18:54 UTC by nmimran99

feat:core: allow market to burn tokens without approval

Allow the market (token contract owner) to burn token without token owner's approval.
The process checks whether the `msg.sender` is the token contract owner and calls `_burn`, which doesn't require a check for allowance.

2023-02-08 19:15 UTC, ramenforbreakfast requested changes
The contents of this PR are mostly fine, just have some test case modifications.

However, you probably were not aware, but this also impacts `ArbitrageBroker`. The `ArbitrageBroker` in `setMarketValidity` needed to provide approvals to a `PrePOMarket` contract to burn their tokens.

Since this is no longer necessary for `redeem` interactions, we can remove the `LongShortToken` approvals to `market`.

Please add these changes as well to this PR since they are directly related.

2023-02-08 19:15 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/LongShortToken.test.ts
> +    })
Remember, we should try to keep tests in an Arrange/Act/Assert format unless its a one liner like a revert case.

Also, we should aim to not perform fragile checks like .eq(0) here because the checks here assume that the beginning supply would just be TEST_AMOUNT.

```suggestion
    it('allows token contract owner to burn user tokens without approval', async () => {
      const userBalanceBefore = await longShort.balanceOf(user.address)
      const totalSupplyBefore = await longShort.totalSupply()
      await longShort.connect(user).approve(deployer.address, 0)
      
      const tx = await longShort.connect(deployer).burnFrom(user.address, TEST_AMOUNT)
      
      expect(tx)
        .emit(longShort.address, 'Transfer')
        .withArgs(user.address, ZERO_ADDRESS, TEST_AMOUNT)
      expect(await longShort.balanceOf(user.address)).eq(userBalanceBefore.sub(TEST_AMOUNT))
      expect(await longShort.totalSupply()).eq(totalSupplyBefore.sub(TEST_AMOUNT))
    })
```

2023-02-08 19:15 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/LongShortToken.test.ts
> +    it('reverts if burner != token owner and burner != token contract owner', async () => {
```suggestion
    it('reverts if insufficient allowance and burner != owner', async () => {
```
This I believe is a more concise and accurate way to write this, since its not that `burner != token owner` would mean a burn reverts, its specifically when a burner doesn't have sufficient allowance.

Also need to add assertions at the beginning that verify these assumptions.

2023-02-09 23:41 UTC, ramenforbreakfast approved these changes
LGTM, can you also remove any use of the `approveTokensForRedemption` in the `PrePOMarket.test.ts`, since we no longer need to rely on approvals for redemption?

**Please rebase or merge changes from main as the PrePOMarket test has been updated recently.**

2023-02-09 23:41 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/LongShortToken.test.ts
> +      await expect(longShort.connect(user2).burnFrom(user.address, TEST_AMOUNT)).to.revertedWith(
```suggestion
      
      await expect(longShort.connect(user2).burnFrom(user.address, TEST_AMOUNT)).to.revertedWith(
```

2023-02-10 06:11 UTC, XavierEkkel approved these changes
LGTM after @ramenforbreakfast's comments

2023-02-10 19:27 UTC, ramenforbreakfast approved these changes
LGTM except 1 comment, you can merge afterwards!

2023-02-10 19:27 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +    const attachTokensForRedemption = async (
What I meant by removing the token approvals in the `PrePOMarket.test.ts` was that you can remove the entire function. There isn't any point to leaving this function since it just attaches to contracts and returns nothing.

2023-02-15 08:16 UTC, merged