feat: add PortfolioValue component to `/portfolio-next`
prepo-io/prepo-monorepo pull request #862
Opened 2023-02-09 13:41 UTC by MeLlamoPablo

PR in draft because I want to:

* add skeletons
* do more testing

-----

![Screenshot 2023-02-09 at 14 40 01](https://user-images.githubusercontent.com/11708035/217828386-d556f236-18d4-477f-80e4-43f152835aef.png)

# FE PR Checklist

- [ ] Self-reviewed each line of code, preempted questions about logic or decisions
- [ ] Noted any intentional deviations from design
- [ ] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [ ] Tested on supported device sizes
    - [ ] iPhone 12 Pro
    - [ ] iPad Air
    - [ ] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [ ] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [ ] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [ ] (if browser specific logic) Tested on Brave, Firefox, Safari
- [ ] (if styling) Tested Light/Dark mode

2023-02-10 07:14 UTC, chrisling-dev requested changes
- When wallet isn't connected, let's make all values show `-`
- Let's use primaryLight for button color so it's readable in dark mode

<img width="293" alt="Screenshot 2023-02-10 at 2 30 55 PM" src="https://user-images.githubusercontent.com/81092286/218019367-c1b165d6-8106-4616-8a71-bbeabd8cc331.png">

2023-02-10 07:14 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          <BigValue>{toUsd(portfolioValue)}</BigValue>
good point on > 99M exceeding the box, can use `compactNumber` util function here to make it show `123.45M`

the `compactNumber` has maximumFractionDigits option set as 2, could you help set minimumFractionDigits to 2 as well so it's always 2 decimals

```suggestion
          <BigValue>${compactNumber(+portfolioValue)}</BigValue>
```

2023-02-10 07:14 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +            <Value>{toUsd(tradingPositionsValue)}</Value>
ditto can use compactNumber
```suggestion
            <Value>${compactNumber(tradingPositionsValue)}</Value>
```

2023-02-10 07:14 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +            <Value>{toUsd(tokenBalanceFormat)}</Value>
ditto

```suggestion
            <Value>${compactNumber(tokenBalanceFormat)}</Value>
```

2023-02-10 07:14 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +      <Flex justifyContent="space-between" width="100%">
Let's use Grid here otherwise it looks weird on table that the cash balance is all the way at the end
```suggestion
      <Grid gridTemplateColumns="repeat(2, 1fr)" width="100%">
```

2023-02-10 09:10 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          <BigValue>{toUsd(portfolioValue)}</BigValue>
Good catch, I also set it to currency = USD since every place where we used it we prepended a dollar sign. Removed that hardcoded dollar sign and renamed the function to `compactUsd`.

I don't like that now it shows $1.1K instead of $1100,00. I think thousands are compact enough to display them fully. If that's fine by you, I'll create a ticket and add more logic and tests in another PR to solve this.

2023-02-10 09:11 UTC, MeLlamoPablo commented
> When wallet isn't connected, let's make all values show `-`

Good catch

2023-02-10 10:50 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          <BigValue>{toUsd(portfolioValue)}</BigValue>
ohh we should keep $ out of it because there will definitely be use case where we need to show compacted value without dollar sign (e.g. when we migrate sales page later, we will need to show `12.34K PPO staked`

As for $1.1k vs $1100, I think we should let it compact when above 999.99 because some number can be fatter and wont fit on smaller screen (e.g. 2888)

2023-02-10 11:03 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          <BigValue>{toUsd(portfolioValue)}</BigValue>
> ohh we should keep $ out of it because there will definitely be use case where we need to show compacted value without dollar sign (e.g. when we migrate sales page later, we will need to show 12.34K PPO staked

I did this to avoid the `$-10K` issue, maybe we can have `compactNumber(value, { showUsdSign: true })`?

2023-02-13 04:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          <BigValue>{toUsd(portfolioValue)}</BigValue>
good point, yeap `showUsdSign` solution sounds good to me, it should default to false or undefined tho, and only show dollar sign when explicitly specified, since not every use case uses the dollar sign.

2023-02-13 05:01 UTC, chrisling-dev requested changes
LGTM after comments

2023-02-13 05:01 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/utils/number-utils.ts
> +export function compactUsd(value: number): string {
as discussed, prefer to keep compactNumber but either with option `showUsdSign` or take an optional NumberFormatOptions and do this:

```
   function compactNumber(value: number, options: Intl.NumberFormatOptions = {}) {

     return Intl.NumberFormat(undefined, {
       notation: 'compact',
       maximumFractionDigits: 2,
       minimumFractionDigits: 2,
       ...options
      }).format(value)
    }
```

2023-02-13 14:06 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/portfolio/PortfolioValue.tsx
> +          )}
Good catch, I missed this when refactoring

2023-02-13 14:11 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/utils/number-utils.ts
> +export function compactUsd(value: number): string {
Gone with the first option. I think it's a good habit to wrap libraries with abstractions that we own (so, not exposing `Intl.NumberFormatOptions`). I guess it's fine since this is a browser API, but this is the approach I'd follow with libraries.

2023-02-14 07:30 UTC, chrisling-dev approved these changes
LGTM

2023-02-14 11:00 UTC, merged