feat: show chart by default and hide settings
prepo-io/prepo-monorepo pull request #870
Opened 2023-02-13 11:34 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=6b4403e1ecc748a48a63e32a1f35e012&p=8b71fbd4d9984794964289e326777633&pm=s

2023-02-13 11:35 UTC, chrisling-dev reviewed
self reviewed

2023-02-13 16:26 UTC, MeLlamoPablo requested changes
Let's also hide the close button from the chart. If you click it, there's no way to restore it.

![Screenshot 2023-02-13 at 17 25 30](https://user-images.githubusercontent.com/11708035/218514331-3dae3bda-aa13-4ba8-86c8-5afe7c1de37a.png)

I don't understand why would we offer that option to the user. Why not always show the chart? What does the user have to gain by hiding it?

2023-02-14 10:53 UTC, chrisling-dev commented
> Let's also hide the close button from the chart. If you click it, there's no way to restore it.
> 
> ![Screenshot 2023-02-13 at 17 25 30](https://user-images.githubusercontent.com/11708035/218514331-3dae3bda-aa13-4ba8-86c8-5afe7c1de37a.png)
> 
> I don't understand why would we offer that option to the user. Why not always show the chart? What does the user have to gain by hiding it?

ohh ya should've removed the close button, thanks!

2023-02-14 11:01 UTC, MeLlamoPablo approved these changes

2023-02-15 04:17 UTC, merged