feat: align underscores
prepo-io/prepo-monorepo pull request #881
Opened 2023-02-14 15:19 UTC by nmimran99

feat: align underscores for contracts

Align the usage of underscores according to variables and functions naming convention.
https://www.notion.so/prepo/Smart-Contract-Handbook-73d78c1d6eec46e2adb225d7162b48c4?pvs=4#3f4e9cfda0354a00aa4e375e08c18d6f

2023-02-14 21:21 UTC, ramenforbreakfast requested changes
Missing changes for `PrePOMarket.sol` which also has missing underscores

2023-02-15 17:05 UTC, XavierEkkel approved these changes
LGTM after comment and if all tests pass (please add PR title prefix)

2023-02-15 17:05 UTC, XavierEkkel commented on apps/smart-contracts/core/contracts/PrePOMarketFactory.sol
> +    return validCollateral[collateral];
the mappings are also private variables, so they should have underscores too

2023-02-15 19:09 UTC, ramenforbreakfast approved these changes
LGTM, except `validCollateral` and `deployedMarkets` need to be underscored in `PrePOMarketFactory.sol` and the below change.

2023-02-15 19:11 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/interfaces/IPrePOMarket.sol
> +   * @param longAmount Amount of Long tokens to redeem
`_amount` in `mint` needs to be `amount`

2023-02-16 13:16 UTC, merged