Feat/simulator summary
prepo-io/prepo-monorepo pull request #883
Opened 2023-02-15 08:01 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=6b4403e1ecc748a48a63e32a1f35e012&p=f15c9b5a8c7c474dac75e07aacd1884d&pm=s

2023-02-15 10:35 UTC, MeLlamoPablo requested changes

2023-02-15 10:35 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +      </SummaryRecord>
We may want to add `loading` if:

* A market is selected BUT
* The data for that market hasn't loaded yet

In this video, you can see a super small window (around second 3) where the valuation from the market hasn't loaded, but the summary switches from `???` -> `$$$` instead of `Skeleton` -> `$$$`



https://user-images.githubusercontent.com/11708035/219000673-ba12cc22-71ff-462b-a5f2-3f173e72688d.mp4

<img width="1067" alt="Screenshot 2023-02-15 at 11 22 33" src="https://user-images.githubusercontent.com/11708035/219001017-164ac15d-7af6-4b0d-bf1a-902fdd467d0b.png">

Granted, the chances of this happening are very small, so feel free to disregard.

2023-02-15 10:35 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +          {(Math.abs(pnlPercentage) * 100).toFixed(2)}%
```suggestion
          {Intl.NumberFormat(undefined, {
            maximumFractionDigits: 2,
            minimumFractionDigits: 2,
            signDisplay: 'always',
            style: 'percent',
          }).format(pnlPercentage)}
```

Probably better to delegate this logic to the broswer?

2023-02-15 10:35 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +    } = {}
I'm not sure why do we need the `prefix` override for if we assign it dynamically depending on whether the number is positive (regardless of whether we use the `Intl` API or not)

I tried to remove this locally and I didn't notice any behavior changes.

If we want to be defensive about not showing negative numbers on "max profit" we can do `Math.max(0, maxProfit)`, but I don't see a scenario where we would want to put `+` on a negative number.

2023-02-15 11:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +    } = {}
I use a prefix override solution here to make sure max profit will always have a `+` and max loss will always have a `-`, the Intl.NumberFormat will show + prefix when value is 0 which is not ideal for max loss case, but thanks for pointing out!

2023-02-15 11:30 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +    } = {}
But feel free to suggest another solution if you think the Intl.NumberFormat could solve the reasoning I stated, agree it's better to delegate to browser if possible

2023-02-15 11:31 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +    } = {}
Then we can do `signDisplay: 'exceptZero'`

2023-02-15 11:45 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +    } = {}
Okay, I get it now. Yeah, I don't think it's possible to ever have `-0` with NumberFormat, so let's keep the current approach. 

![Screenshot 2023-02-15 at 12 45 04](https://user-images.githubusercontent.com/11708035/219018697-51c51f67-75e8-4d22-bbc5-1ff407eb63ef.png)

2023-02-15 11:46 UTC, MeLlamoPablo approved these changes
Approving since the other comment is not a blocker

2023-02-16 03:03 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/simulator/SimulatorSummary.tsx
> +      </SummaryRecord>
oh sry somehow my previous comment wasn't submitted, the behaviour is intended because the values in simulator may often become undefined when trade size changes, so we decided to just show ??? for any empty state here and use the loading skeleton in the trade component to indicate loading, otherwise the ux might be annoying if everything keeps changing to skeleton, but thanks for pointing out!

2023-02-16 03:03 UTC, merged