feat: implement global deposit cap
prepo-io/prepo-monorepo pull request #885
Opened 2023-02-15 11:43 UTC by MeLlamoPablo

This PR implements the global deposit cap. To keep things small, the user deposit cap will be implemented in a separate PR.

### Scenario 1: global cap already reached

![Screenshot 2023-02-15 at 12 21 03](https://user-images.githubusercontent.com/11708035/219014580-81e78a87-747b-4a5b-8ec8-db81b8c706b3.png)

### Scenario 2: global cap would be exceeded by deposit

https://user-images.githubusercontent.com/11708035/219014649-1af6321e-1d28-4869-943b-2bd13c9c9480.mp4

### How to update the mock contract for testing

Go to the [code on Etherscan](https://goerli.etherscan.io/address/0x1412039d105c41d19f8c77aebdc118a5945aba6a#code) and follow these steps:

https://user-images.githubusercontent.com/11708035/219015015-17993350-d5f4-4b51-9392-f5e4647cedf0.mp4

# FE PR Checklist

- [ ] Self-reviewed each line of code, preempted questions about logic or decisions
- [ ] Noted any intentional deviations from design
- [ ] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [ ] Tested on supported device sizes
    - [ ] iPhone 12 Pro
    - [ ] iPad Air
    - [ ] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [ ] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [ ] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [ ] (if browser specific logic) Tested on Brave, Firefox, Safari
- [ ] (if styling) Tested Light/Dark mode

2023-02-15 11:53 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    <Icon name="info" color="warning" width={spacingIncrement(20)} height={spacingIncrement(20)} />
@chrisling-dev intentional deviation from design:

This button here is an ℹ️ while on the design it's an !

I can't find an icon like on the design. Should I submit a separate PR to `prepo-ui`?

2023-02-15 11:53 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +      />
@chrisling-dev intentional deviation from design:

![Screenshot 2023-02-15 at 12 53 22](https://user-images.githubusercontent.com/11708035/219020425-3bd8ab17-b175-44e3-9892-8cbb8d5f3672.png)

The tooltip is missing, what should I put?

2023-02-15 16:58 UTC, MeLlamoPablo commented
I'm not sure [why the deploy is failing](https://github.com/prepo-io/prepo-monorepo/actions/runs/4183504866/jobs/7248112772), @chrisling-dev could you confirm? I don't have access to Vercel.

2023-02-16 03:25 UTC, chrisling-dev requested changes

2023-02-16 03:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +import { spacingIncrement } from 'prepo-ui'
I'm not sure why the build is failing (not recognizing the `prepo-ui/lib/src` path on vercel but works locally, could you try importing from prepo-ui instead of `lib/src`

```suggestion
import styled from 'styled-components'
import { Alert as BaseAlert, Icon, spacingIncrement } from 'prepo-ui'
```

2023-02-16 04:53 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    <Icon name="info" color="warning" width={spacingIncrement(20)} height={spacingIncrement(20)} />
Can include in the same PR the `!` icon

2023-02-16 08:25 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +import { spacingIncrement } from 'prepo-ui'
Good catch! That seems to be it. It was an auto-import from the IDE, maybe I need to restrict imports from `/lib/src`

2023-02-16 09:53 UTC, chrisling-dev requested changes

2023-02-16 09:53 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }
not strongly opinionated here but I think I saw somewhere in mobx's docs (forgot where to find it) that it's better to do

const { globalNetDepositAmount } = this.root.depositRecordStore

rather than copying it to a new variable.

Not strongly opinionated tho, feel free to disregard

2023-02-16 09:54 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }
Interesting, I don't see how it's different javascript-wise, but I'll research it a bit

2023-02-16 10:05 UTC, chrisling-dev requested changes
Could we try centering the text and icon like in the design?

2023-02-16 10:05 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +  }
Should've mentioned earlier that the underline in figma is inaccurate, somehow their text rendering engine forces a lot of space between underline and text, it should just be a simple underline, the code below works perfectly fine:

```suggestion
  all: unset;
  color: ${({ theme }): string => theme.color.primaryLight};
  cursor: pointer;
  text-decoration: underline;
  transition: none;

  :hover {
    color: ${({ theme }): string => theme.color.darkPrimaryLight};
  }
```

2023-02-16 10:05 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +      font-weight: ${({ theme }): number => theme.fontWeight.medium};
Let's give it 16px line height

```suggestion
    .ant-alert-message {
      line-height: ${spacingIncrement(16)};
      font-size: ${({ theme }): string => theme.fontSize.xs};
      font-weight: ${({ theme }): number => theme.fontWeight.medium};
```

2023-02-16 10:10 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }
nvm forget about this, I found it and it only matter when we're running in a tracked function, in this case what you're doing is fine

2023-02-16 10:11 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    <Icon name="info" color="warning" width={spacingIncrement(20)} height={spacingIncrement(20)} />
Huh so I thought I needed to publish `prepo-ui` to NPM for that to work, turns out I was just missing a `yarn install` lol

2023-02-16 10:17 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +  }
Huh, that makes it a lot simpler. Sometimes Figma does feel inaccurate in that it doesn't look exactly the same when you implement the design.

Also, I kept the `:focus` since we're using `all: unset`, so we need to give it a focus state for accessibility.

2023-02-17 03:19 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +  }
yea I read about Figma's engineering blogs back then, they have a custom text rendering engine solution which is different than actual browser implementation

2023-02-17 03:38 UTC, chrisling-dev approved these changes
LGTM after adding `isProduction` check

2023-02-17 03:38 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
should we add a production check here so it doesn't affect the current behaviour?

```suggestion
    // TODO: remove this when contract is updated
    if (isProduction()) return 'no'
```

2023-02-17 03:39 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +      />
I've posted in FE channel to ask for copy of tooltip, for now let's leave it out and add on in a separate PR since it's hidden in production anyway

2023-02-17 09:08 UTC, merged