feat: implement user deposit cap
prepo-io/prepo-monorepo pull request #886
Opened 2023-02-15 16:57 UTC by MeLlamoPablo

🚧 WIP - This PR is in a decent, working state but I need to do more testing and polish

Blocked by #885

2023-02-20 09:02 UTC, chrisling-dev requested changes
When showing "exceeded-if-deposit", wdyt if we show whichever limit that is smaller? Currently it's a bit weird that when I exceed global limit (100k) and click on it, it shows another limit $500, then I have to click the $500 again to be able to deposit.

2023-02-20 09:57 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/abi/depositRecord.abi.json
> +  {
Sure! Where can I get that from?

2023-02-20 12:37 UTC, MeLlamoPablo commented
Those are great suggestions! I've updated the code

> When showing "exceeded-if-deposit", wdyt if we show whichever limit that is smaller? Currently it's a bit weird that when I exceed global limit (100k) and click on it, it shows another limit $500, then I have to click the $500 again to be able to deposit.

Done. I've implemented a small "priority system" on `DepositWarning`, I think that was the most readable way I could come up with. The logic is now:

* If the global cap has been already exceeded, show that warning.
* If the user cap has been already exceeded, show that warning.
* If depositing would exceed any of the two caps, show the warning for the cap with the least remaining amount. (Even if depositing would exceed both caps).
* Otherwise, don't show warnings

> Thoughts on making a function called "getDepositLimit", which accepts any string/number value, and returns an object:
> 
> ```
>   state: 'exceeded-if-deposit' | 'already-exceeded' | ...,
>   amount?: ...
> ```
> 
> So the UI could potentially be simpler, and it's just a matter of some JS check to return the right value in mobx store?
> 
> Also that the limit check and etc can be reused by open trade page when deposit + trade is implementated

[Refactored to this](https://github.com/prepo-io/prepo-monorepo/blob/a9392de633f2234040261a2efcfada60cbc8ff73/apps/frontend/core-dapp/src/features/deposit/DepositStore.ts#L166-L207), what do you think?

I think it's nice because it simplified `DepositStore` and the `DepositWarning` component. Now there aren't a lot of properties scattered around. Every property is grouped nicely into `globalDepositLimitInfo` and `userDepositLimitInfo`

2023-02-20 13:25 UTC, chrisling-dev commented on apps/frontend/core-dapp/abi/depositRecord.abi.json
> +  {
Oh you need to go to `prepo-monorepo/apps/smart-contracts/core`, run `yarn` which generates the artifacts, and find it in `artifacts/contracts/DepositRecord.sol/DepositRecord.json`:

```
[
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "contract IAccountList",
          "name": "accountList",
          "type": "address"
        }
      ],
      "name": "AccountListChange",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "hook",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "allowed",
          "type": "bool"
        }
      ],
      "name": "AllowedHooksChange",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "cap",
          "type": "uint256"
        }
      ],
      "name": "GlobalNetDepositCapChange",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "previousAdminRole",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "newAdminRole",
          "type": "bytes32"
        }
      ],
      "name": "RoleAdminChanged",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "newRoleAdminNominee",
          "type": "bytes32"
        }
      ],
      "name": "RoleAdminNomineeUpdate",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "name": "RoleGranted",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "nominated",
          "type": "bool"
        }
      ],
      "name": "RoleNomineeUpdate",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "name": "RoleRevoked",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "cap",
          "type": "uint256"
        }
      ],
      "name": "UserDepositCapChange",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "DEFAULT_ADMIN_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "SET_ACCOUNT_LIST_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "SET_ALLOWED_HOOK_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "SET_GLOBAL_NET_DEPOSIT_CAP_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "SET_USER_DEPOSIT_CAP_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        }
      ],
      "name": "acceptRole",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        }
      ],
      "name": "acceptRoleAdmin",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getAccountList",
      "outputs": [
        {
          "internalType": "contract IAccountList",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getGlobalNetDepositAmount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getGlobalNetDepositCap",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        }
      ],
      "name": "getRoleAdmin",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        }
      ],
      "name": "getRoleAdminNominee",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "getRoleMember",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
     [...]

2023-02-20 13:31 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/abi/depositRecord.abi.json
> +  {
Cool! Yeah, we should use the proper ABI, and if my mock is implemented correctly, this change should be transparent.

Btw, I changed it to `IDepositRecord`, not `DepositRecord`. I believe that's all the frontend should need.

2023-02-21 03:40 UTC, chrisling-dev requested changes

2023-02-21 03:40 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
We should be able to simplify this further, it should just take an input number, without the cap.

With the input number, we can just check
- if something isnt ready, return { status: 'loading' }
- if globalCapExceeded return { status: 'global-exceeded', capInUsd, amountInUsd }
- if userCapExceeded return { status: 'user-exceeded', capInUsd, amountInUsd }
- if inputWouldExceedEitherGlobalOrUser return { status: 'exceeded-if-deposit, remainingAmountInUsd: Math.min(globalRemainingAmount, userRemainingAmount)
- return 'not-exceeded'

Then reusing this would be straightforward, we can just do
```
get depositLimitInfo() {
    return this. getDepositLimitInfo(depositAmount)
 }
```

reusing the logic in deposit + trade later
```
get depositTradeLimitInfo() {
    return this. getDepositLimitInfo(tradeAmount)
 }
```

And UI code would be as simple as:
```
switch(depositLimt.status) {
  case 'global-exceeded':
    return <GlobalExceededUI />
  case 'user-exceeded':
    return <UserExceededUI />
  case 'exceeded':
    return "Deposit limit exceeded. Only xxx remaining" UI
  default:
    return null
}
```

Combining everything for max reusability, the usage would only take 2 lines here and 2 lines in open + trade page later:

```
  const { depositLimitInfo } = depositStore

  ... 
  return <>
     <DepositWarning depositLimit={depositLimitInfo} />
  <>
```

Let me know if this makes sense or am I missing something here

2023-02-21 03:40 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
This way in depositDisabled check we don't have to check 2 separate caps (global and user), and can just check the deposit limit info object

Also I think global + user cap should be computed together and never separated because they are directly relevant

2023-02-21 03:40 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +  const warnings: Array<{ element: ReactElement; priority: number }> = []
I think the priority system is an overkill and somewhat hard to read, would it be easier if there's only one object that gives 'global-cap-exceeded', 'user-cap-exceeded', 'exceed-if-deposit'

And we just do a switch here?

```
switch(depositLimit.status) {
    case 'global-cap-exceeded':
    ...
}
```

2023-02-21 08:27 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
Mm the reason I did this separate was so that I could reuse the same logic for the withdraw cap... Let me think about how to make your suggestion and the withdraw cap compatible.

2023-02-21 08:31 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
ohh gotcha, what about combing both userDepositLimitInfo and globalDepositLimitInfo to achieve returning one single object rather than relying on 2 separate computed values?

2023-02-21 08:32 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
btw 'already-exceeded' for both global and user cap has the same UI so it can just return the same name if we do the single object approach

There's a slight UI mismatch in this PR in that, it has different copy for global and personal deposit limit when it has already exceeded

2023-02-21 08:35 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
I see that the copies are different in this PR? ([user](https://github.com/prepo-io/prepo-monorepo/pull/886/files#diff-dfc6a0930a7dc3ae01d96be39baca961d758215af8cbbec640a2b8f5582ad60dR94-R106) and [global](https://github.com/prepo-io/prepo-monorepo/pull/886/files#diff-dfc6a0930a7dc3ae01d96be39baca961d758215af8cbbec640a2b8f5582ad60dR122-R132))

2023-02-21 08:39 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
> I see that the copies are different in this PR? ([user](https://github.com/prepo-io/prepo-monorepo/pull/886/files#diff-dfc6a0930a7dc3ae01d96be39baca961d758215af8cbbec640a2b8f5582ad60dR94-R106) and [global](https://github.com/prepo-io/prepo-monorepo/pull/886/files#diff-dfc6a0930a7dc3ae01d96be39baca961d758215af8cbbec640a2b8f5582ad60dR122-R132))

They should be the same copy for both user and global cap

![Screenshot 2023-02-21 at 4 38 45 PM](https://user-images.githubusercontent.com/81092286/220292053-d73d2742-2b91-4dbf-a62e-778c959c4d0c.png)

2023-02-21 10:52 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +  }: {
I've given this another pass, and I think it looks much better thanks to your suggestions :)

Here's what I've done:

* I've extracted the logic that computes individual limits into a [reusable pure function](https://github.com/prepo-io/prepo-monorepo/blob/636db71f2e45e0ae863d9435d286f21746dd4400/apps/frontend/core-dapp/src/utils/balance-limits.ts#L14-L55)
  * It could be reused by the withdraw store to calculate the withdraw cap
* I've kept the [`globalDepositLimitInfo` and `userDepositLimitInfo`](https://github.com/prepo-io/prepo-monorepo/blob/636db71f2e45e0ae863d9435d286f21746dd4400/apps/frontend/core-dapp/src/features/deposit/DepositStore.ts#L148-L186) computed values in `DepositStore`, which now bridge data to this utility function. But now they are private and not accessible by the UI.
* I've added a [`depositLimit` computed value](https://github.com/prepo-io/prepo-monorepo/blob/636db71f2e45e0ae863d9435d286f21746dd4400/apps/frontend/core-dapp/src/features/deposit/DepositStore.ts#L188-L228) that combines the global and user limits into one and decides which one to show following the logic you outlined.

    Basically, the logic that was done in the UI is now done in the store.
* Now `DepositWarning` consists of [a dumb switch that just displays data](https://github.com/prepo-io/prepo-monorepo/blob/636db71f2e45e0ae863d9435d286f21746dd4400/apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx#L58-L102).

Let me know what you think!

2023-02-21 12:22 UTC, chrisling-dev approved these changes
nice work! LGTM

2023-02-21 12:22 UTC, merged