feat: show PPO reward on deposit
prepo-io/prepo-monorepo pull request #891
Opened 2023-02-16 17:49 UTC by MeLlamoPablo

![Screenshot 2023-02-16 at 18 42 33](https://user-images.githubusercontent.com/11708035/219445565-d9e095dd-a806-4998-99e7-00c572c98680.png)

This PR shows the PPO reward on the deposit page, if applicable. The screenshot above assumes a price of `$0.10` per `$PPO` and a deposit fee of 2%, hence the user is compensated with 20 PPO.

I have deployed [a mock `TokenSender` contract
](https://goerli.etherscan.io/address/0xe8ccbbbe6dcc8b88484c8bc7e3bcfa1c431092d7#code) which we currently use to compute the reward.

### ⚠️ Important

The current front-end implementation uses a hypothetical `getScaledPrice` view function that doesn't exist yet on `TokenSender.sol`. I proposed it earlier and [Xavier thinks it's a good idea](https://discord.com/channels/846183492714889307/1072114526448799814/1075752259960459274). If this PR gets approved, I'll submit a proposal PR so that the SC team can evaluate it.

**If we decide not to implement `getScaledPrice`, this PR in its current state will not work and we will need to revisit it.**

# FE PR Checklist

- [X] Self-reviewed each line of code, preempted questions about logic or decisions
- [X] Noted any intentional deviations from design
- [X] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [X] Tested on supported device sizes
    - [X] iPhone 12 Pro
    - [X] iPad Air
    - [X] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [X] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [X] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [ ] (if browser specific logic) Tested on Brave, Firefox, Safari
- [X] (if styling) Tested Light/Dark mode

2023-02-17 08:34 UTC, chrisling-dev requested changes
Overall UI and logic LGTM, but I think it should show loading indicator when we're checking for ppo reward. Since ppo reward and estimated received amount depends on different values, it is possible for estimated received amount to complete it's loading before ppo reward which causes a weird behaviour like in the video

https://user-images.githubusercontent.com/81092286/219594130-ac169e97-8a06-4a94-9c3e-d47a893c09cf.mov

2023-02-17 08:34 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/TokenSenderStore.ts
> +  private get scaledPriceIfActive(): BigNumber | undefined {
I think can name this to scaledPrice so you don't need to rename the variable name in calculateReward

```suggestion
  private get scaledPrice(): BigNumber | undefined {
```

2023-02-17 08:34 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/TokenSenderStore.ts
> +    return scaledPrice.lte(scaledPriceLowerBound) ? undefined : scaledPrice
I'm thinking we should use undefined to indicate loading and 'zero' value to indicate there's no reward and that we should hide the reward text when there's no reward. So I'd probably return 0 here 

```suggestion
    return scaledPrice.lte(scaledPriceLowerBound) ? BigNumber.from(0) : scaledPrice
```

2023-02-17 08:34 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/TokenSenderStore.ts
> +    return feeInUsd.mul(BigNumber.from(10).pow(ppoDecimals)).div(scaledPrice)
then I'd probably do this here:
```suggestion
    if(scaledPrice.eq(0)) return BigNumber.from(0)
    return feeInUsd.mul(BigNumber.from(10).pow(ppoDecimals)).div(scaledPrice)
```

2023-02-17 08:34 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositSummary.tsx
> +      )}
And refactor this to:

```suggestion
      {(ppoReward === undefined || +ppoReward > 0) && (
        <SummaryRecord label="PPO Reward" loading={ppoReward === undefined || depositFees === undefined} tooltip={<PPOReward />}>
          <PPORewardAmount>
            {Intl.NumberFormat(undefined, {
              maximumFractionDigits: 2,
              minimumFractionDigits: 1,
              signDisplay: 'exceptZero',
            }).format(+(ppoReward ?? '0'))}
          </PPORewardAmount>
          &nbsp; ({toUsd(depositFees ?? 0)})
        </SummaryRecord>
      )}
```

Note that the `ppoReward ?? 0` and `depositFees ?? 0` don't matter because when we pass loading as true (when ppoReward or depositFees is undefined), the UI is overriden by a loading skeleton.

2023-02-17 08:34 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositStore.ts
> +    if (depositFeesBN === undefined || depositFeesBN.eq(0)) return undefined
And the return 0 here?

```suggestion
    if (depositFeesBN === undefined || depositFeesBN.eq(0)) return '0'
```

2023-02-17 11:40 UTC, MeLlamoPablo commented
Great suggestions! Thanks for the review.

2023-02-20 11:57 UTC, chrisling-dev approved these changes
LGTM after some nits

2023-02-20 11:57 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositSummary.tsx
> +        If the reward is zero, there's no reward so we show nothing.
```suggestion
        if reward is undefined, show loading skeleton.
        if has reward, show reward UI.
        If no reward, show nothing
```

2023-02-20 11:57 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/lib/core-contracts.ts
> +  // A dummy contract for testing purposes only.
Let's add a TODO here
```suggestion
  // TODO: update to actual contract address
  // A dummy contract for testing purposes only.
```

2023-02-20 11:57 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/TokenSenderStore.ts
> +    if (scaledPrice.eq(0)) return BigNumber.from(0)
Might want to return scaledPrice instead of a new BigNumber object to keep it's observability, since both are 0 anyway. scaledPrice is observable because it's from a computed value, but BigNumber.from(0) isn't observable and may cause the component observing the returned value to stop observing it

```suggestion
    if (scaledPrice.eq(0)) return scaledPrice
```

2023-02-20 12:01 UTC, chrisling-dev approved these changes

2023-02-20 12:01 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositSummary.tsx
> +            }).format(+(ppoReward ?? '0'))}
Let's also use `notation: compact` so it fits on mobile

2023-02-20 15:04 UTC, merged