style: make DepositWarning's InlineTextButton hoverable on dark mode
prepo-io/prepo-monorepo pull request #896
Opened 2023-02-17 09:25 UTC by MeLlamoPablo

`primaryLight` and `darkPrimaryLight` are the same color on dark mode, which means that the `InlineTextButton` can't be visibly focused or hovered on dark mode.

Previous behavior:

https://user-images.githubusercontent.com/11708035/219605290-def80ab0-8b3f-4a51-bfeb-2001956637db.mp4

New behavior:

https://user-images.githubusercontent.com/11708035/219605335-6762f183-5611-447f-8021-09e7ed15d422.mp4

2023-02-17 09:36 UTC, chrisling-dev requested changes

2023-02-17 09:36 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    color: ${({ theme }): string => theme.color.info};
nice catch but we don't use this pattern anywhere tho, for consistency purpose (e.g. deposit/withdraw link on portfolio page) I think we should keep darkPrimaryLight for now, and perhaps add another color pair for hovering that turns light purple in dark mode to darker purple

2023-02-17 09:36 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    color: ${({ theme }): string => theme.color.info};
I don't mind keep it as is for now, and we'll add another ticket later to update all light purple hovering to make sure everything is consistent

2023-02-17 09:39 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    color: ${({ theme }): string => theme.color.info};
Hovering is not the problem, it's focusing. We need to give some focus feedback for accessibility. The Deposit/Withdraw links also have this problem.

2023-02-17 09:40 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    color: ${({ theme }): string => theme.color.info};
> and perhaps add another color pair for hovering that turns light purple in dark mode to darker purple

Also, I'm not sure if making it darker on focus is the way to go, since it may not be accessible for colorblind people. We may want a color that is more catchy. Alternatively, we could add a border to these elements on focus.

2023-02-20 12:04 UTC, chrisling-dev approved these changes
good point on accessibility

2023-02-20 12:04 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/deposit/DepositWarning.tsx
> +    color: ${({ theme }): string => theme.color.info};
not a fan of border, I think this is ok then, LGTM

2023-02-20 12:13 UTC, merged