feat: allow trading w usdc or preCT
prepo-io/prepo-monorepo pull request #902
Opened 2023-02-18 09:44 UTC by chrisling-dev

https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=6b4403e1ecc748a48a63e32a1f35e012&p=a05afb27388e449ebd9481676ceedb89&pm=s

2023-02-20 09:54 UTC, MeLlamoPablo requested changes
Looks great overall! Some small comments

2023-02-20 09:54 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +`
This is duplicated from `SlideUpRow`. Is this intentional? I think that, as a quick solution, we could export the components from `SlideUpRow` (even if the components are unrelated) so that at least the relationship is established in code. Then, if the components evolve in different ways we could decide to duplicate them.

2023-02-20 09:54 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
I would probably pull this into a child component that observes the `tokensStore`, like `<TokenBalance token={token} />`, considering that we don't use `tokenStore` or `balance` anywhere else in this component.

2023-02-20 09:54 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
Also, this doesn't seem right for ETH (I have 2.15 ETH, not $2.15 ETH).

![Screenshot 2023-02-20 at 10 31 02](https://user-images.githubusercontent.com/11708035/220066868-85dcb4af-c27e-40d5-bccd-667f756e93a8.png)

We need to convert the ETH price to dollars (I'd argue that we also need to convert the USDC price to dollars in case it goes off-peg)

2023-02-20 10:52 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +`
yeap intentional, SlideUpRow takes market entity and handle a bunch of stuffs like position direction, valuation and etc, so I duplicated this  rather than trying to make SlideUpRow reusable. It should've been renamed to MarketPositionRow really, but I reckon we could leave the refactor for separate PR/when we clean things up

2023-02-20 10:53 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
Good point

2023-02-20 10:55 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
ahh yes you're right, I left this here to test that we can list non-erc20 token here (e.g. native eth) in a way that still keeps the observability of everything, it should've been removed)

2023-02-20 12:12 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
After our sync today, I think we can merge this and deal with units later

2023-02-20 12:12 UTC, MeLlamoPablo approved these changes

2023-02-21 04:16 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/currencies/CurrencyRow.tsx
> +    balanceUI = <Balance>{compactNumber(+balance, { showUsdSign: true })}</Balance>
I've removed ETH for now

2023-02-21 04:17 UTC, merged