fix:core: withdraw amount limited by global limit
prepo-io/prepo-monorepo pull request #906
Opened 2023-02-20 14:55 UTC by nmimran99

fix:core: withdraw amount limited by global limit

This PR fixes the issue where a user can essentially withdraw an amount larger than the global withdraw limit if the withdraw is the first one in the period.

2023-02-21 06:21 UTC, ramenforbreakfast reviewed
@nmimran99 Could you please add a test or modify a test so that it catches this? Clearly our tests were missing an important case so we'd want to add one to verify it given this fix.

2023-02-21 06:26 UTC, ramenforbreakfast requested changes
Going to request changes here since we should have additional tests.

2023-02-21 18:02 UTC, ramenforbreakfast commented
Spoke about this on our call, but will add here an official reminder.
@nmimran99 needs to add a test case to ensure a user cannot deposit beyond the global limit just because a period has changed (which is what we did not test for and what caused the bug to get past).

2023-02-21 19:00 UTC, XavierEkkel approved these changes
LGTM after comments and after LGT @ramenforbreakfast

2023-02-21 19:00 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/WithdrawHook.test.ts
> +        .hook(user.address, user.address, TEST_USER_WITHDRAW_LIMIT, TEST_USER_WITHDRAW_LIMIT)
```suggestion
        .hook(user.address, user.address, 0, 0)
```
should work, since the limit is already exceeded

2023-02-22 02:35 UTC, ramenforbreakfast approved these changes
LGTM

2023-02-22 09:35 UTC, merged