chore:core: add tests for recipient in hooks
prepo-io/prepo-monorepo pull request #907
Opened 2023-02-20 15:22 UTC by nmimran99

chore:core: add tests for recipient in hooks
This PR adds tests to hooks that can have the `funder` and `recipient` as 2 different users. 
The tests are focused on the parts where the difference comes in play.

2023-02-21 06:34 UTC, ramenforbreakfast requested changes
So we also should check that the contracts calling hooks pass the correct parameters, I see in the  `Collateral.test.ts` we've already done this (I guess you added it in the initial PR #882?), but if you look in the `PrePOMarket.test.ts`, we are still using the same account when testing hook parameters.

2023-02-21 06:34 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/DepositHook.test.ts
> +        .hook(user.address, user.address, TEST_AMOUNT_BEFORE_FEE, TEST_AMOUNT_AFTER_FEE)
I think this is a mistake, shouldn't the second parameter here be recipient.address? As well as the expect statement?

2023-02-21 17:43 UTC, ramenforbreakfast approved these changes
LGTM

2023-02-22 14:33 UTC, XavierEkkel approved these changes
LGTM after nits

2023-02-22 14:33 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/DepositHook.test.ts
> +      expect(user.address).not.eq(recipient.address)
```suggestion
      expect(user.address).not.eq(recipient.address)
      
```

2023-02-22 14:33 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/RedeemHook.test.ts
> +        expect(user.address).not.eq(recipient.address)
```suggestion
        expect(user.address).not.eq(recipient.address)
        
```

2023-02-22 14:33 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/RedeemHook.test.ts
add to the above test `and redeemer = recipient`

2023-02-22 14:33 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/RedeemHook.test.ts
> +      it('calls tokenSender.send() if fee > 0 and funder != recipient', async () => {
```suggestion
      it('calls tokenSender.send() if fee > 0 and redeemer != recipient', async () => {
```

2023-02-22 14:33 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/WithdrawHook.test.ts
add to the above test `and funder = recipient`

2023-02-22 16:01 UTC, merged