feat: add withdraw cap
prepo-io/prepo-monorepo pull request #910
Opened 2023-02-20 16:55 UTC by MeLlamoPablo

Blocked by #886 

🚧 WIP

2023-02-22 12:07 UTC, chrisling-dev requested changes

2023-02-22 12:07 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +        resetsIn: periodAlreadyReset ? undefined : timeToReset,
if periodAlreadyReset is returned above with status = 'not-exceeded', do we still need this check here?

```suggestion
        resetsIn: timeToReset,
```

2023-02-22 12:07 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawWarning.tsx
> +              )}
would resetsIn ever be undefined here for both 'already-exceeded' and 'exceeded-after-transfer' if combined with the solutions I provided earlier?

2023-02-22 12:42 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +      currentAmount: periodAlreadyReset ? BigNumber.from(0) : globalAmountWithdrawnThisPeriod,
Even if `periodAlreadyReset = true`, it is possible that the user would want to withdraw more than `globalWithdrawLimitPerPeriod` (in which case the status would be `exceeded-after-transfer`)

If we returned early `not-exceeded` here we wouldn't prevent the user from making a deposit bigger than `globalWithdrawLimitPerPeriod`

2023-02-22 12:43 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +        resetsIn: periodAlreadyReset ? undefined : timeToReset,
As explained above, we can't return `not-exceeded` if `periodAlreadyReset`

2023-02-22 12:44 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawWarning.tsx
> +              )}
The case where `resetsIn` can be undefined is: (considering a period of 24h and a limit of `$100`)

* Last reset: 3 days ago (therefore we are in a new period)
* I'm trying to withdraw `$200`

Therefore the cap info is:

* `status = exceeded-after-deposit`
* `resetsIn = undefined`

2023-02-22 12:50 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +      formatUnits: this.root.preCTTokenStore.formatUnits.bind(this.root.preCTTokenStore),
It doesn't work without `.bind` for me

![Screenshot 2023-02-22 at 13 47 36](https://user-images.githubusercontent.com/11708035/220623874-27c13271-403d-434b-a9e5-818f000e2e38.png)

2023-02-23 07:16 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +      formatUnits: this.root.preCTTokenStore.formatUnits.bind(this.root.preCTTokenStore),
oo okie thanks for checking!

2023-02-23 07:24 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +      currentAmount: periodAlreadyReset ? BigNumber.from(0) : globalAmountWithdrawnThisPeriod,
ahh okay I based my logic off an older version of the code where amount doesn't matter if you're not within the withdrawal window, this makes sense then

the older version logic:
![Screenshot 2023-02-23 at 3 24 18 PM](https://user-images.githubusercontent.com/81092286/220842787-1ab8954d-ad42-4208-b5ca-2db7f5bbcd88.png)

2023-02-23 07:49 UTC, chrisling-dev approved these changes
LGTM after matching copy to design, well done!

2023-02-23 07:49 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawWarning.tsx
> +              <p>Global withdraw limit reached ({cap})</p>
```suggestion
              <p>Global withdrawal limit reached ({cap})</p>
              <br />
```

2023-02-23 07:49 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawWarning.tsx
> +                Withdraw limit exceeded. <br />
```suggestion
                Withdrawal limit exceeded. <br />
```

2023-02-23 07:49 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawWarning.tsx
> +              </p>
```suggestion
                (
                <InlineTextButton
                  onClick={(): void => {
                    setWithdrawalAmount(withdrawLimit.remainingUnits)
                  }}
                  title={`Withdraw ${formattedRemainingAmount} instead`}
                >
                  {formattedRemainingAmount}
                </InlineTextButton>{' '}
                remaining)
              </p>
```

2023-02-23 07:54 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/withdraw/WithdrawStore.ts
> +      currentAmount: periodAlreadyReset ? BigNumber.from(0) : globalAmountWithdrawnThisPeriod,
Oh yeah, I saw that the audit placed a high severity issue on this, so I just assumed that this code would be changed

2023-02-23 08:09 UTC, chrisling-dev approved these changes
✅

2023-02-23 09:11 UTC, merged