chore:core: add tests for todos in prepo market
prepo-io/prepo-monorepo pull request #918
Opened 2023-02-21 21:57 UTC by nmimran99

chore:core: add tests for todos in prepo market

Add 2 tests regarding different fee levels of redeem hook and the amount of collateral the redeemer is getting based on the fee taken.

The PR adds a `TestRedeemHook.sol` contract that acts as a hook that keeps 50% of the fees to make the test possible

2023-02-22 02:33 UTC, ramenforbreakfast requested changes

2023-02-22 02:33 UTC, ramenforbreakfast commented on apps/smart-contracts/core/contracts/test/TestRedeemHook.sol
> +contract TestRedeemHook is
Ok I think you made this unnecessarily complicated. This contract only needs to inherit `IHook`, and implement a `hook`. The hook can just `transferFrom(msg.sender, address(this), fee - 1)`.

2023-02-22 02:33 UTC, ramenforbreakfast commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +      // TestRedeemHook meant to take 50% of the fee
So given that you simplify the `TestRedeemHook` contract you created, you don't need to reinitialize all these things. You can just set the `redeemHook` of the `prePOMarket` already deployed to the test redeem hook for the purposes of the test, and set it back to the actual one later if need be.

2023-02-22 17:25 UTC, ramenforbreakfast approved these changes
LGTM, can you remove TODOs as well? I think we can forego the full fee transfer testcase.

2023-02-22 18:51 UTC, XavierEkkel commented on apps/smart-contracts/core/contracts/test/TestRedeemHook.sol
> +  /// @notice this contract is a test contract made to test a use case where the redeem hook only takes a part of the fee
nit: move comment above the `contract TestRedeemHook` line

2023-02-22 18:51 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +      expect(await collateralToken.balanceOf(user.address)).to.eq(totalOwed.sub(expectedPartialFee))
also check the `Redemption` event emitted here

2023-02-22 18:51 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +      )
also check the `Redemption` event emitted here

2023-02-22 18:51 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +      await prePOMarket.connect(user).redeem(longToRedeem, shortToRedeem, user.address)
```suggestion
      const totalOwed = await calculateTotalOwed(longToRedeem, shortToRedeem, false)
      expect(totalOwed).to.be.gt(0)
      const redeemFee = calculateFee(totalOwed, await prePOMarket.getRedemptionFee())
      expect(redeemFee).to.be.gt(0)
      
      await prePOMarket.connect(user).redeem(longToRedeem, shortToRedeem, user.address)
```

2023-02-22 18:51 UTC, XavierEkkel commented on apps/smart-contracts/core/test/unit/PrePOMarket.test.ts
> +      expect(await collateralToken.balanceOf(user.address)).to.eq(totalOwed.sub(expectedPartialFee))
also check treasury collateral balance change (like in test below)

2023-02-24 16:25 UTC, XavierEkkel approved these changes
LGTM

2023-02-24 16:25 UTC, merged