feat: implement redeeming position for resolved markets
prepo-io/prepo-monorepo pull request #944
Opened 2023-02-24 16:50 UTC by MeLlamoPablo

This PR implements redeeming resolved markets (markets whose `finalLongPayout` is defined). Here'a [Loom (3m26s)](https://www.loom.com/share/488d4539f4764d148b2dfd4bea3818d0) demonstrating how does it work and giving a brief overview of the most relevant code changes.

<img width="1134" alt="Screenshot 2023-02-24 at 17 49 40" src="https://user-images.githubusercontent.com/11708035/221238276-e5140090-b866-4e83-9004-55213032ce76.png">

Note: I need to do more testing before merging but this is in a reviewable state

# FE PR Checklist

- [ ] Self-reviewed each line of code, preempted questions about logic or decisions
- [ ] Noted any intentional deviations from design
- [ ] Tried hard to break it and failed, think like a malicious user trying to find edge cases to break the app
- [ ] Tested on supported device sizes
    - [ ] iPhone 12 Pro
    - [ ] iPad Air
    - [ ] 1920x1080 (how to add custom size: [https://umaar.com/dev-tips/51-add-new-device/](https://umaar.com/dev-tips/51-add-new-device/))
- [ ] Tested all widths between 1920px wide to 390px wide and confirmed no weird breakages at widths in between
- [ ] (if related to balances) Tested with empty wallet, modest wallet, whale wallet
- [ ] (if browser specific logic) Tested on Brave, Firefox, Safari
- [ ] (if styling) Tested Light/Dark mode

2023-02-27 06:29 UTC, chrisling-dev requested changes

2023-02-27 06:29 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +import { makeError } from 'prepo-utils/lib/src'
You might wanna import from `prepo-utils`

```suggestion
import { makeError } from 'prepo-utils'
```

2023-02-27 07:33 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +import { makeError } from 'prepo-utils/lib/src'
Thanks! I need to see if I can stop my IDE from auto importing from there...

2023-02-27 09:51 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/close-trade/ClosePositionSummary.tsx
> +        tooltip={isMarketResolved ? undefined : <EstimatedValuation />}
Intentional deviation from design: I haven't added tooltips to these because I don't know the copies

![Screenshot 2023-02-27 at 10 50 13](https://user-images.githubusercontent.com/11708035/221530791-9b0a1d01-804f-408d-b84d-048eba825625.png)

2023-02-27 12:23 UTC, chrisling-dev requested changes

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    )
If market is resolved user should just redeem whatever they have remaining in that market. So it should just redeem with user's long/short balance I reckon, remember to add a `balance === undefined` check above

```suggestion
    const { error } = await selectedMarket.redeem(
      this.direction === 'long' ?  this.selectedMarket.longTokenBalanceBN : BigNumber.from(0),
      this.direction === 'short' ? this.selectedMarket.shortTokenBalanceBN : BigNumber.from(0)
    )
```

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    )
oh it does seem we also have to pass a recipient as a third parameter?

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    )
my bad, the third parameter is only when we migrate to new interfaces, could you add a TODO comment above to add signer's address as recipient later when we switch to new interfaces?

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +  }
Maybe we could just use user's balance here instead of relying on closePositionAmountBN? You could use the `this.selectedPosition.token.balanceOfSigner` which will select the direction for you so you don't have to do `direction === 'long'`

```suggestion
    if (
      finalLongPrice === undefined ||
      maxPrice === undefined ||
      this.selectedPosition.token.balanceOfSigner === undefined
    ) {
      return undefined
    }

    return this.selectedPosition.token.balanceOfSigner.mul(maxPrice.sub(finalLongPrice)).div(maxPrice)
  }
```

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    return this.redeemPositionAmountOutBN ?? this.closePositionMarketAmountOutBN
do we need some sort of `if(marker resolved) return redeemPositionAmountOut else return closePositionMarketAmountOut` here?

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/close-trade/CloseTrade.tsx
> +const DebugControls = observer(() => {
very interesting way of debugging! Could you move this into it's on file please so it's more organized here

2023-02-27 12:23 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +      // To indicate a null value (since 0 could be a valid finalLongPrice)
```suggestion
      // return a null value to indicate market hasn't resolved
```

2023-02-27 12:37 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeButton.tsx
> +    if (selectedMarket.resolved) return 'Market Closed'
Mm I can't remember... I may have made this up. Doesn't it make sense though? Since we haven't actually implemented on-chain expiration. If the market is resolved, why would we say "Market Expired"?

2023-02-27 12:41 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    )
In this case `closePositionAmountBN` equals `longTokenBalanceBN`/`shortTokenBalanceBN`, but I agree that your way is clearer.

2023-02-27 12:47 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +      // To indicate a null value (since 0 could be a valid finalLongPrice)
I think that changes the meaning of my comment. I'm not saying "this line returns a null value". I'm saying "to the smart contract, maxPrice + 1 is a null value"

Maybe I could reword it like this so it is less confusing:

```ts
// The smart contract initially sets finalLongPrice to maxPrice + 1
// to indicate the absence of a final price (since 0 could be a valid finalLongPrice)
```

2023-02-27 13:03 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +  }
We still need the direction because the formula is different. The amount of collateral you get for your position is:

* For long positions: `long tokens * final long payout %`
* For short positions: `short tokens * (1 - final long payout %)`

But yeah, I agree that relying on `selectedPosition.token.balanceOfSigner` is simpler and clearer than on `closePositionAmoutnBN`

2023-02-27 13:04 UTC, MeLlamoPablo commented on apps/frontend/core-dapp/src/features/trade/TradeStore.ts
> +    return this.redeemPositionAmountOutBN ?? this.closePositionMarketAmountOutBN
No, `redeemPositionAmountOutBN` will be undefined if `finalLongPrice` is undefined. We could do that but I'd say this way is simpler.

2023-02-28 02:05 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +      // To indicate a null value (since 0 could be a valid finalLongPrice)
ohh gotcha 👍

2023-02-28 03:16 UTC, chrisling-dev approved these changes
Great job! LGTM!

2023-02-28 03:16 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/stores/entities/MarketEntity.ts
> +      return undefined
minor comment to make this shorter and more readable

```suggestion
    // The smart contract initially sets finalLongPrice to maxPrice + 1
    // To indicate a null value (since 0 could be a valid finalLongPrice)
    if (finalLongPrice.gt(maxPrice)) return undefined
```

2023-02-28 04:21 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeButton.tsx
> +    if (selectedMarket.resolved) return 'Market Closed'
hmm I'll get back to you on this today

2023-02-28 07:39 UTC, chrisling-dev commented on apps/frontend/core-dapp/src/features/trade/open-trade/OpenTradeButton.tsx
> +    if (selectedMarket.resolved) return 'Market Closed'
Okay confirmed that we'll use "Market Closed"

2023-02-28 07:48 UTC, merged